<?php
/**
 * Canonical asset registry (human-edited).
 * Keep this stable; generated SRI can live in cdn.generated.php.
 */
return [
	/**
	 * -- -- ^ -- -- ^ -- -- ^ -- -- ^ -- -- ^ -- -- ^ -- -- ^ -- -- ^ -- --
	 *        Base assets - only used as dependancies of other assets
	 * -- -- ^ -- -- ^ -- -- ^ -- -- ^ -- -- ^ -- -- ^ -- -- ^ -- -- ^ -- --
	 */
	\p2m\assets\base\P2DataTablesAutoFillBaseAsset::class => [
		'name'       => 'P2DataTablesAutoFillBase',
		'type'       => 'cdn',
		'version'    => '2.7.0',
		'baseUrl'    => 'https://cdn.datatables.net/autofill/{version}',
		'css'        => ['css/autoFill.bootstrap5.min.css'],
		'js'         => ['js/dataTables.autoFill.min.js'],
		'deps'       => [\p2m\assets\P2DataTablesBootstrap5Asset::class],
		'notes'      => 'Base for P2DataTablesAutoFillAsset',
	],
	\p2m\assets\base\P2DataTablesBaseAsset::class => [
		'name'       => 'P2DataTablesBase',
		'type'       => 'cdn',
		'version'    => '2.3.5',
		'baseUrl'    => 'https://cdn.datatables.net/{version}',
		'css'        => [],
		'js'         => ['js/dataTables.min.js'],
		'deps'       => [\p2m\assets\P2CoreAsset::class],
		'notes'      => 'Base for P2DataTablesAsset',
	],
	\p2m\assets\base\P2DataTablesButtonsBaseAsset::class => [
		'name'       => 'P2DataTablesButtonsBase',
		'type'       => 'cdn',
		'version'    => '3.2.2',
		'baseUrl'    => 'https://cdn.datatables.net/buttons/{version}',
		'css'        => ['css/buttons.bootstrap5.min.css'],
		'js'         => ['js/dataTables.buttons.min.js'],
		'deps'       => [\p2m\assets\P2DataTablesBootstrap5Asset::class],
		'notes'      => 'Base for P2DataTablesButtonsAsset',
	],
	\p2m\assets\base\P2DataTablesResponsiveBaseAsset::class => [
		'name'       => 'P2DataTablesResponsiveBase',
		'type'       => 'cdn',
		'version'    => '3.0.4',
		'baseUrl'    => 'https://cdn.datatables.net/responsive/{version}',
		'css'        => ['css/responsive.bootstrap5.min.css'],
		'js'         => ['js/dataTables.responsive.min.js'],
		'deps'       => [\p2m\assets\P2DataTablesBootstrap5Asset::class],
		'notes'      => 'Base for P2DataTablesResponsiveAsset',
	],
	\p2m\assets\base\P2DataTablesSearchBuilderBaseAsset::class => [
		'name'       => 'P2DataTablesSearchBuilderBase',
		'type'       => 'cdn',
		'version'    => '1.8.2',
		'baseUrl'    => 'https://cdn.datatables.net/searchbuilder/{version}',
		'css'        => ['css/searchBuilder.bootstrap5.min.css'],
		'js'         => ['js/dataTables.searchBuilder.min.js'],
		'deps'       => [\p2m\assets\P2DataTablesBootstrap5Asset::class],
		'notes'      => 'Base for P2DataTablesSearchBuilderAsset',
	],
	\p2m\assets\base\P2DataTablesSearchPanesBaseAsset::class => [
		'name'       => 'P2DataTablesSearchPanesBase',
		'type'       => 'cdn',
		'version'    => '2.3.3',
		'baseUrl'    => 'https://cdn.datatables.net/searchpanes/{version}',
		'css'        => ['css/searchPanes.bootstrap5.min.css'],
		'js'         => ['js/dataTables.searchPanes.min.js'],
		'deps'       => [\p2m\assets\P2DataTablesBootstrap5Asset::class],
		'notes'      => 'Base for P2DataTablesSearchPanesAsset',
	],
	\p2m\assets\base\P2DataTablesStateRestoreBaseAsset::class => [
		'name'       => 'P2DataTablesStateRestoreBase',
		'type'       => 'cdn',
		'version'    => '1.4.1',
		'baseUrl'    => 'https://cdn.datatables.net/staterestore/{version}',
		'css'        => ['css/stateRestore.bootstrap5.min.css'],
		'js'         => ['js/dataTables.stateRestore.min.js'],
		'deps'       => [\p2m\assets\P2DataTablesBootstrap5Asset::class],
		'notes'      => 'Base for P2DataTablesStateRestoreAsset',
	],
	\p2m\assets\base\P2FlagIconsBaseAsset::class => [
		'name'       => 'P2FlagIconsBase',
		'type'       => 'cdn',
		'version'    => '7.5.0',
		'baseUrl'    => 'https://cdnjs.cloudflare.com/ajax/libs/flag-icons/{version}',
		'css'        => ['css/flag-icons.min.css'],
		'js'         => [],
		'deps'       => [\p2m\assets\P2CoreAsset::class],
		'notes'      => 'Base for P2FlagIconsAsset',
	],
	\p2m\assets\base\P2FullCalendarBaseAsset::class => [
		'name'       => 'P2FullCalendarBase',
		'type'       => 'cdn',
		'version'    => '6.1.15',
		'baseUrl'    => 'https://cdn.jsdelivr.net/npm/fullcalendar@{version}',
		'css'        => [],
		'js'         => ['index.global.min.js'],
		'deps'       => [\p2m\assets\P2CoreAsset::class],
		'notes'      => 'Base for P2FullCalendarAsset',
	],
	\p2m\assets\base\P2PdfmakeBaseAsset::class => [
		'name'       => 'P2PdfmakeBase',
		'type'       => 'cdn',
		'version'    => '0.2.7',
		'baseUrl'    => 'https://cdnjs.cloudflare.com/ajax/libs/pdfmake/{version}',
		'css'        => [],
		'js'         => ['pdfmake.min.js'],
		'deps'       => [\p2m\assets\P2CoreAsset::class],
		'notes'      => 'Base for P2PdfmakeAsset',
	],
	/**
	 * -- -- ^ -- -- ^ -- -- ^ -- -- ^ -- -- ^ -- -- ^ -- -- ^ -- -- ^ -- --
	 *                       Primary assets
	 * -- -- ^ -- -- ^ -- -- ^ -- -- ^ -- -- ^ -- -- ^ -- -- ^ -- -- ^ -- --
	 */
	/**
	 * local
	 */
	\p2m\assets\P2CoreAsset::class => [
		'name'       => 'P2Core',
		'type'       => 'local',
		'sourcePath' => '@p2m/assets/lib/p2additions',
		'css'        => ['css/p2additions.min.css'],
		'js'         => [],
		'deps'       => [\yii\web\YiiAsset::class],
		'notes'      => 'Core P2Asset - loads p2additions & YiiAsset',
	],
	\p2m\assets\P2CircleButtonsAsset::class => [
		'name'       => 'P2CircleButtons',
		'type'       => 'local',
		'sourcePath' => '@p2m/assets/lib/circle-buttons',
		'css'        => ['css/circle-buttons.min.css'],
		'js'         => [],
		'deps'       => [\p2m\assets\P2CoreAsset::class],
		'notes'      => 'Asset for CircleButtons',
	],
	\p2m\assets\P2FlagIconsAsset::class => [
		'name'       => 'P2FlagIcons',
		'type'       => 'local',
		'sourcePath' => '@p2m/assets/lib/flag-icons',
		'css'        => ['css/flag-icons.min.css'],
		'js'         => [],
		'deps'       => [\p2m\assets\base\P2FlagIconsBaseAsset::class],
		'notes'      => 'Asset for FlagIcons - extends https://flagicons.lipis.dev/',
	],
	\p2m\assets\P2TimelineAsset::class => [
		'name'       => 'P2Timeline',
		'type'       => 'local',
		'sourcePath' => '@p2m/assets/lib/timeline',
		'css'        => ['css/timeline.min.css'],
		'js'         => [],
		'deps'       => [\p2m\assets\P2CoreAsset::class],
		'notes'      => 'Asset for Timeline',
	],
	/**
	 * Bootstrap
	 */
	\p2m\assets\P2BootstrapAsset::class => [
		'name'       => 'P2Bootstrap',
		'type'       => 'cdn',
		'version'    => '5.3.8',
		'baseUrl'    => 'https://cdn.jsdelivr.net/npm/bootstrap@{version}/dist',
		'css'        => ['css/bootstrap.min.css'],
		'js'         => [],
		'deps'       => [\p2m\assets\P2BootstrapPluginAsset::class],
		'notes'      => 'Asset for Bootstrap 5',
	],
	\p2m\assets\P2BootstrapPluginAsset::class => [
		'name'       => 'P2BootstrapPlugin',
		'type'       => 'cdn',
		'version'    => '5.3.8',
		'baseUrl'    => 'https://cdn.jsdelivr.net/npm/bootstrap@{version}/dist',
		'css'        => [],
		'js'         => ['js/bootstrap.bundle.min.js'],
		'deps'       => [\p2m\assets\P2CoreAsset::class],
		'notes'      => 'Asset for Bootstrap 5 Plugin',
	],
	\p2m\assets\P2BootstrapIconsAsset::class => [
		'name'       => 'P2BootstrapIcons',
		'type'       => 'cdn',
		'version'    => '1.11.3',
		'baseUrl'    => 'https://cdn.jsdelivr.net/npm/bootstrap-icons@{version}/font',
		'css'        => ['bootstrap-icons.css'],
		'js'         => [],
		'deps'       => [\p2m\assets\P2CoreAsset::class],
		'notes'      => 'Asset for Bootstrap Icons',
	],
	/**
	 * others
	 */
	\p2m\assets\P2AnimateAsset::class => [
		'name'       => 'P2Animate',
		'type'       => 'cdn',
		'version'    => '4.1.1',
		'baseUrl'    => 'https://cdn.jsdelivr.net/npm/animate.css@{version}',
		'css'        => ['animate.min.css'],
		'js'         => [],
		'deps'       => [\p2m\assets\P2CoreAsset::class],
		'notes'      => 'Asset for Animate',
	],
	\p2m\assets\P2BootstrapSocialAsset::class => [
		'name'       => 'P2BootstrapSocial',
		'type'       => 'cdn',
		'version'    => '5.1.1',
		'baseUrl'    => 'https://cdn.jsdelivr.net/npm/bootstrap-social@{version}',
		'css'        => ['bootstrap-social.min.css'],
		'js'         => [],
		'deps'       => [\p2m\assets\P2CoreAsset::class],
		'notes'      => 'Asset for Bootstrap Social',
	],
	\p2m\assets\P2Lightbox2Asset::class => [
		'name'       => 'P2Lightbox2',
		'type'       => 'cdn',
		'version'    => '1.8.5',
		'baseUrl'    => 'https://cdn.jsdelivr.net/npm/bs5-lightbox@{version}/dist',
		'css'        => [],
		'js'         => ['index.bundle.min.js'],
		'deps'       => [\p2m\assets\P2CoreAsset::class],
		'notes'      => 'Asset for Lightbox2',
	],
	\p2m\assets\P2ChartJsAsset::class => [
		'name'       => 'P2ChartJs',
		'type'       => 'cdn',
		'version'    => '2.9.4',
		'baseUrl'    => 'https://cdn.jsdelivr.net/npm/chart.js@{version}',
		'css'        => ['dist/Chart.min.css'],
		'js'         => ['dist/Chart.min.js'],
		'deps'       => [\p2m\assets\P2CoreAsset::class],
		'notes'      => 'Asset for ChartJs',
	],
	\p2m\assets\P2DraggabillyAsset::class => [
		'name'       => 'P2Draggabilly',
		'type'       => 'cdn',
		'version'    => '3.0.0',
		'baseUrl'    => 'https://cdn.jsdelivr.net/npm/draggabilly@{version}',
		'css'        => [],
		'js'         => ['draggabilly.min.js'],
		'deps'       => [\p2m\assets\P2CoreAsset::class],
		'notes'      => 'Asset for Draggabilly',
	],
	\p2m\assets\P2EmojiCssAsset::class => [
		'name'       => 'P2EmojiCss',
		'type'       => 'cdn',
		'version'    => '1.0.6',
		'baseUrl'    => 'https://cdn.jsdelivr.net/npm/emoji.css@{version}',
		'css'        => ['dist/emoji.min.css'],
		'js'         => ['lib/index.min.js'],
		'deps'       => [\p2m\assets\P2CoreAsset::class],
		'notes'      => 'Asset for EmojiCss',
	],
	\p2m\assets\P2FitvidsAsset::class => [
		'name'       => 'P2Fitvids',
		'type'       => 'cdn',
		'version'    => '2.1.1',
		'baseUrl'    => 'https://cdn.jsdelivr.net/npm/fitvids@{version}/dist',
		'css'        => [],
		'js'         => ['fitvids.min.js'],
		'deps'       => [\p2m\assets\P2CoreAsset::class],
		'notes'      => 'Asset for Fitvids',
	],
	\p2m\assets\P2FlickityAsset::class => [
		'name'       => 'P2Flickity',
		'type'       => 'cdn',
		'version'    => '3.0.0',
		'baseUrl'    => 'https://cdn.jsdelivr.net/npm/flickity@{version}',
		'css'        => ['css/flickity.min.css'],
		'js'         => ['dist/flickity.pkgd.min.js'],
		'deps'       => [\p2m\assets\P2CoreAsset::class],
		'notes'      => 'Asset for Flickity',
	],
	\p2m\assets\P2GoogleMapsAsset::class => [
		'name'       => 'P2GoogleMaps',
		'type'       => 'cdn',
		'version'    => '4.3.3',
		'baseUrl'    => 'https://cdn.jsdelivr.net/npm/google-maps@{version}/lib/cjs',
		'css'        => [],
		'js'         => ['index.min.js'],
		'deps'       => [\p2m\assets\P2CoreAsset::class],
		'notes'      => 'Asset for Google Maps',
	],
	\p2m\assets\P2HolderJsAsset::class => [
		'name'       => 'P2HolderJs',
		'type'       => 'cdn',
		'version'    => '2.9.9',
		'baseUrl'    => 'https://cdn.jsdelivr.net/npm/holderjs@{version}',
		'css'        => [],
		'js'         => ['holder.min.j'],
		'deps'       => [\p2m\assets\P2CoreAsset::class],
		'notes'      => 'Asset for HolderJs',
	],
	\p2m\assets\P2ImagesLoadedAsset::class => [
		'name'       => 'P2ImagesLoaded',
		'type'       => 'cdn',
		'version'    => '5.0.0',
		'baseUrl'    => 'https://cdn.jsdelivr.net/npm/imagesloaded@{version}',
		'css'        => [],
		'js'         => ['imagesloaded.pkgd.min.js'],
		'deps'       => [\p2m\assets\P2CoreAsset::class],
		'notes'      => 'Asset for ImagesLoaded',
	],
	\p2m\assets\P2InfiniteScrollAsset::class => [
		'name'       => 'P2InfiniteScroll',
		'type'       => 'cdn',
		'version'    => '5.0.0',
		'baseUrl'    => 'https://cdn.jsdelivr.net/npm/infinite-scroll@{version}/dist',
		'css'        => [],
		'js'         => ['infinite-scroll.pkgd.min.js'],
		'deps'       => [\p2m\assets\P2CoreAsset::class],
		'notes'      => 'Asset for InfiniteScroll',
	],
	\p2m\assets\P2IsotopeAsset::class => [
		'name'       => 'P2Isotope',
		'type'       => 'cdn',
		'baseUrl'    => 'https://unpkg.com/isotope-layout@3/dist',
		'css'        => [],
		'js'         => ['isotope.pkgd.min.js'],
		'deps'       => [\p2m\assets\P2CoreAsset::class],
		'notes'      => 'Asset for Isotope',
	],
	\p2m\assets\P2JqueryAsset::class => [
		'name'       => 'P2Jquery',
		'type'       => 'cdn',
		'version'    => '3.7.1',
		'baseUrl'    => 'https://code.jquery.com/{version}',
		'css'        => [],
		'js'         => ['jquery-{version}.min.js'],
		'deps'       => [],
		'notes'      => 'Asset for Jquery',
	],
	\p2m\assets\P2JqueryEasingAsset::class => [
		'name'       => 'P2JqueryEasing',
		'type'       => 'cdn',
		'version'    => '1.4.1',
		'baseUrl'    => 'https://cdn.jsdelivr.net/npm/jquery.easing@{version}',
		'css'        => [],
		'js'         => ['jquery.easing.min.js'],
		'deps'       => [\p2m\assets\P2CoreAsset::class],
		'notes'      => 'Asset for JqueryEasing',
	],
	\p2m\assets\P2JSZipAsset::class => [
		'name'       => 'P2JSZip',
		'type'       => 'cdn',
		'version'    => '3.10.1',
		'baseUrl'    => 'https://cdnjs.cloudflare.com/ajax/libs/jszip/{version}',
		'css'        => [],
		'js'         => ['jszip.min.js'],
		'deps'       => [\p2m\assets\P2CoreAsset::class],
		'notes'      => 'Asset for JSZip',
	],
	\p2m\assets\P2Lightbox2Asset::class => [
		'name'       => 'P2Lightbox2',
		'type'       => 'cdn',
		'version'    => '2.11.5',
		'baseUrl'    => 'https://cdn.jsdelivr.net/npm/lightbox2@{version}/dist',
		'css'        => ['css/lightbox.min.css'],
		'js'         => ['js/lightbox.min.js'],
		'deps'       => [\p2m\assets\P2CoreAsset::class],
		'notes'      => 'Asset for Lightbox2',
	],
	\p2m\assets\P2MagnificPopupAsset::class => [
		'name'       => 'P2MagnificPopup',
		'type'       => 'cdn',
		'version'    => '1.2.0',
		'baseUrl'    => 'https://cdn.jsdelivr.net/npm/magnific-popup@{version}/dist',
		'css'        => ['magnific-popup.min.css'],
		'js'         => ['jquery.magnific-popup.min.js'],
		'deps'       => [\p2m\assets\P2CoreAsset::class],
		'notes'      => 'Asset for MagnificPopup',
	],
	\p2m\assets\P2MasonryAsset::class => [
		'name'       => 'P2Masonry',
		'type'       => 'cdn',
		'version'    => '4.2.2',
		'baseUrl'    => 'https://cdn.jsdelivr.net/npm/masonry-layout@{version}/dist',
		'css'        => [],
		'js'         => ['masonry.pkgd.min.js'],
		'deps'       => [\p2m\assets\P2CoreAsset::class],
		'notes'      => 'Asset for Masonry',
	],
	\p2m\assets\P2MathJsAsset::class => [
		'name'       => 'P2MathJs',
		'type'       => 'cdn',
		'version'    => '4.4.0',
		'baseUrl'    => 'https://cdn.jsdelivr.net/npm/mathjs@1{version}/lib/browser',
		'css'        => [],
		'js'         => ['math.min.js'],
		'deps'       => [\p2m\assets\P2CoreAsset::class],
		'notes'      => 'Asset for MathJs',
	],
	\p2m\assets\P2MetisMenuAsset::class => [
		'name'       => 'P2MetisMenu',
		'type'       => 'cdn',
		'version'    => '3.0.7',
		'baseUrl'    => 'https://cdn.jsdelivr.net/npm/metismenu@{version}/dist',
		'css'        => ['metisMenu.min.css'],
		'js'         => ['metisMenu.min.js'],
		'deps'       => [\p2m\assets\P2CoreAsset::class],
		'notes'      => 'Asset for MetisMenu',
	],
	\p2m\assets\P2MorrisAsset::class => [
		'name'       => 'P2Morris',
		'type'       => 'cdn',
		'version'    => '0.5.0',
		'baseUrl'    => 'https://cdn.jsdelivr.net/npm/morris.js@{version}',
		'css'        => ['morris.min.css'],
		'js'         => ['morris.min.js'],
		'deps'       => [\p2m\assets\P2CoreAsset::class],
		'notes'      => 'Asset for Morris',
	],
	\p2m\assets\P2PackeryAsset::class => [
		'name'       => 'P2Packery',
		'type'       => 'cdn',
		'version'    => '3.0.0',
		'baseUrl'    => 'https://cdn.jsdelivr.net/npm/packery@{version}/dist',
		'css'        => [],
		'js'         => ['packery.pkgd.min.js'],
		'deps'       => [\p2m\assets\P2CoreAsset::class],
		'notes'      => 'Asset for Packery',
	],
	\p2m\assets\P2PdfMakeAsset::class => [
		'name'       => 'P2PdfMake',
		'type'       => 'cdn',
		'version'    => '0.2.7',
		'baseUrl'    => 'https://cdnjs.cloudflare.com/ajax/libs/pdfmake/{version}',
		'css'        => [],
		'js'         => ['vfs_fonts.js'],
		'deps'       => [\p2m\assets\base\P2PdfmakeBaseAsset::class],
		'notes'      => 'Asset for PdfMake',
	],
	\p2m\assets\P2QunitAsset::class => [
		'name'       => 'P2Qunit',
		'type'       => 'cdn',
		'version'    => '2.24.1',
		'baseUrl'    => 'https://cdn.jsdelivr.net/npm/qunit@{version}/qunit',
		'css'        => ['qunit.min.css'],
		'js'         => ['qunit.min.js'],
		'deps'       => [\p2m\assets\P2CoreAsset::class],
		'notes'      => 'Asset for Qunit',
	],
	\p2m\assets\P2RaphaelAsset::class => [
		'name'       => 'P2Raphael',
		'type'       => 'cdn',
		'version'    => '2.3.0',
		'baseUrl'    => 'https://cdn.jsdelivr.net/npm/raphael@{version}',
		'css'        => [],
		'js'         => ['raphael.min.js'],
		'deps'       => [\p2m\assets\P2CoreAsset::class],
		'notes'      => 'Asset for Raphael',
	],
	\p2m\assets\P2ScrollRevealAsset::class => [
		'name'       => 'P2ScrollReveal',
		'type'       => 'cdn',
		'version'    => '4.0.9',
		'baseUrl'    => 'https://cdn.jsdelivr.net/npm/scrollreveal@{version}/dist',
		'css'        => [],
		'js'         => ['scrollreveal.min.js'],
		'deps'       => [\p2m\assets\P2CoreAsset::class],
		'notes'      => 'Asset for ScrollReveal',
	],
	\p2m\assets\P2SimpleDatatablesAsset::class => [
		'name'       => 'P2SimpleDatatables',
		'type'       => 'cdn',
		'version'    => '0.2.0',
		'baseUrl'    => 'https://cdn.jsdelivr.net/npm/simple-datatables@1{version}/dist',
		'css'        => ['style.min.css'],
		'js'         => ['umd/simple-datatables.min.js'],
		'deps'       => [\p2m\assets\P2CoreAsset::class],
		'notes'      => 'Asset for SimpleDatatables',
	],
	\p2m\assets\P2SimpleLineIconsAsset::class => [
		'name'       => 'P2SimpleLineIcons',
		'type'       => 'cdn',
		'version'    => '2.5.5',
		'baseUrl'    => 'https://cdn.jsdelivr.net/npm/simple-line-icons@{version}',
		'css'        => ['css/simple-line-icons.min.css'],
		'js'         => ['scripts/build.min.js'],
		'deps'       => [\p2m\assets\P2CoreAsset::class],
		'notes'      => 'Asset for SimpleLineIcons',
	],
	\p2m\assets\P2SweetAlertAsset::class => [
		'name'       => 'P2SweetAlert',
		'type'       => 'cdn',
		'version'    => '2.1.2',
		'baseUrl'    => 'https://cdn.jsdelivr.net/npm/sweetalert@{version}/dist',
		'css'        => [],
		'js'         => ['sweetalert.min.js'],
		'deps'       => [\p2m\assets\P2CoreAsset::class],
		'notes'      => 'Asset for SweetAlert',
	],
	\p2m\assets\P2TimelineJs3Asset::class => [
		'name'       => 'P2TimelineJs3',
		'type'       => 'cdn',
		'version'    => '3.4.0',
		'baseUrl'    => 'https://cdn.jsdelivr.net/npm/timelinejs3@{version}/compiled',
		'css'        => ['css/timeline.min.css'],
		'js'         => ['js/timeline-min.min.js'],
		'deps'       => [\p2m\assets\P2CoreAsset::class],
		'notes'      => 'Asset for TimelineJs3',
	],
	\p2m\assets\P2WowAsset::class => [
		'name'       => 'P2Wow',
		'type'       => 'cdn',
		'version'    => '1.1.3',
		'baseUrl'    => 'https://cdn.jsdelivr.net/npm/wowjs@{version}',
		'css'        => ['css/libs/animate.min.css'],
		'js'         => ['dist/wow.min.js'],
		'deps'       => [\p2m\assets\P2CoreAsset::class],
		'notes'      => 'Asset for Wow',
	],
	/**
	 * -- -- ^ -- -- ^ -- -- ^ -- -- ^ -- -- ^ -- -- ^ -- -- ^ -- -- ^ -- --
	 *                       DataTables assets
	 * -- -- ^ -- -- ^ -- -- ^ -- -- ^ -- -- ^ -- -- ^ -- -- ^ -- -- ^ -- --
	 */
	\p2m\assets\datatables\P2DataTablesBootstrap5Asset::class => [
		'name'       => 'P2DataTablesBootstrap5',
		'type'       => 'cdn',
		'version'    => '2.3.5',
		'baseUrl'    => 'https://cdn.datatables.net/{version}',
		'css'        => ['css/dataTables.bootstrap5.min.css'],
		'js'         => ['js/dataTables.bootstrap5.min.js'],
		'deps'       => [\p2m\assets\base\P2DataTablesBaseAsset::class],
		'notes'      => 'Asset for DataTables Bootstrap5',
	],
	\p2m\assets\datatables\P2DataTablesAutoFillAsset::class => [
		'name'       => 'P2DataTablesAutoFill',
		'type'       => 'cdn',
		'version'    => '2.7.0',
		'baseUrl'    => 'https://cdn.datatables.net/autofill/{version}',
		'css'        => [],
		'js'         => ['js/autoFill.bootstrap5.min.js'],
		'deps'       => [\p2m\assets\base\P2DataTablesAutoFillBaseAsset::class],
		'notes'      => 'Asset for DataTables AutoFill',
	],
	\p2m\assets\datatables\P2DataTablesButtonsAsset::class => [
		'name'       => 'P2DataTablesButtons',
		'type'       => 'cdn',
		'version'    => '3.2.2',
		'baseUrl'    => 'https://cdn.datatables.net/buttons/{version}',
		'css'        => [],
		'js'         => ['js/buttons.bootstrap5.min.js'],
		'deps'       => [\p2m\assets\base\P2DataTablesButtonsBaseAsset::class],
		'notes'      => 'Asset for DataTables Buttons',
	],
	\p2m\assets\datatables\P2DataTablesColReorderAsset::class => [
		'name'       => 'P2DataTablesColReorder',
		'type'       => 'cdn',
		'version'    => '2.0.4',
		'baseUrl'    => 'https://cdn.datatables.net/colreorder/{version}',
		'css'        => ['css/colReorder.bootstrap5.min.css'],
		'js'         => ['js/dataTables.colReorder.min.js'],
		'deps'       => [\p2m\assets\datatables\P2DataTablesBootstrap5Asset::class],
		'notes'      => 'Asset for DataTables ColReorder',
	],
	\p2m\assets\datatables\P2DataTablesColVisAsset::class => [
		'name'       => 'P2DataTablesColVis',
		'type'       => 'cdn',
		'version'    => '2.2.2',
		'baseUrl'    => 'https://cdn.datatables.net/{version}',
		'css'        => [],
		'js'         => ['js/buttons.colVis.min.js'],
		'deps'       => [\p2m\assets\datatables\P2DataTablesButtonsAsset::class],
		'notes'      => 'Asset for DataTables ColVis',
	],
	\p2m\assets\datatables\P2DataTablesDateTimeAsset::class => [
		'name'       => 'P2DataTablesDateTime',
		'type'       => 'cdn',
		'version'    => '1.5.5',
		'baseUrl'    => 'https://cdn.datatables.net/datetime/{version}',
		'css'        => ['css/dataTables.dateTime.min.css'],
		'js'         => ['js/dataTables.dateTime.min.js'],
		'deps'       => [\p2m\assets\datatables\P2DataTablesBootstrap5Asset::class],
		'notes'      => 'Asset for DataTables DateTime',
	],
	\p2m\assets\datatables\P2DataTablesFixedColumnsAsset::class => [
		'name'       => 'P2DataTablesFixedColumns',
		'type'       => 'cdn',
		'version'    => '5.0.4',
		'baseUrl'    => 'https://cdn.datatables.net/fixedcolumns/{version}',
		'css'        => ['css/fixedColumns.bootstrap5.min.css'],
		'js'         => ['js/dataTables.fixedColumns.min.js'],
		'deps'       => [\p2m\assets\datatables\P2DataTablesBootstrap5Asset::class],
		'notes'      => 'Asset for DataTables FixedColumns',
	],
	\p2m\assets\datatables\P2DataTablesFixedHeaderAsset::class => [
		'name'       => 'P2DataTablesFixedHeader',
		'type'       => 'cdn',
		'version'    => '4.0.1',
		'baseUrl'    => 'https://cdn.datatables.net/fixedheader/{version}',
		'css'        => ['css/fixedHeader.bootstrap5.min.css'],
		'js'         => ['js/dataTables.fixedHeader.min.js'],
		'deps'       => [\p2m\assets\datatables\P2DataTablesBootstrap5Asset::class],
		'notes'      => 'Asset for DataTables FixedHeader',
	],
	\p2m\assets\datatables\P2DataTablesHtml5ExportAsset::class => [
		'name'       => 'P2DataTablesHtml5Export',
		'type'       => 'cdn',
		'version'    => '3.2.2',
		'baseUrl'    => 'https://cdn.datatables.net/buttons/{version}',
		'css'        => [],
		'js'         => ['js/buttons.html5.min.js'],
		'deps'       => [\p2m\assets\datatables\P2DataTablesButtonsAsset::class],
		'notes'      => 'Asset for DataTables Html5Export',
	],
	\p2m\assets\datatables\P2DataTablesKeyTableAsset::class => [
		'name'       => 'P2DataTablesKeyTable',
		'type'       => 'cdn',
		'version'    => '2.12.1',
		'baseUrl'    => 'https://cdn.datatables.net/keytable/{version}',
		'css'        => ['css/keyTable.bootstrap5.min.css'],
		'js'         => ['js/dataTables.keyTable.min.js'],
		'deps'       => [\p2m\assets\datatables\P2DataTablesBootstrap5Asset::class],
		'notes'      => 'Asset for DataTables KeyTable',
	],
	\p2m\assets\datatables\P2DataTablesPrintAsset::class => [
		'name'       => 'P2DataTablesPrint',
		'type'       => 'cdn',
		'version'    => '3.2.2',
		'baseUrl'    => 'https://cdn.datatables.net/buttons/{version}',
		'css'        => [],
		'js'         => ['js/buttons.print.min.js'],
		'deps'       => [\p2m\assets\datatables\P2DataTablesButtonsAsset::class],
		'notes'      => 'Asset for DataTables Print',
	],
	\p2m\assets\datatables\P2DataTablesResponsiveAsset::class => [
		'name'       => 'P2DataTablesResponsive',
		'type'       => 'cdn',
		'version'    => '3.0.4',
		'baseUrl'    => 'https://cdn.datatables.net/responsive/{version}',
		'css'        => [],
		'js'         => ['js/responsive.bootstrap5.js'],
		'deps'       => [\p2m\assets\base\P2DataTablesResponsiveBaseAsset::class],
		'notes'      => 'Asset for DataTables Responsive',
	],
	\p2m\assets\datatables\P2DataTablesRowGroupAsset::class => [
		'name'       => 'P2DataTablesRowGroup',
		'type'       => 'cdn',
		'version'    => '1.5.1',
		'baseUrl'    => 'https://cdn.datatables.net/rowgroup/{version}',
		'css'        => ['css/rowGroup.bootstrap5.min.css'],
		'js'         => ['js/dataTables.rowGroup.min.js'],
		'deps'       => [\p2m\assets\datatables\P2DataTablesBootstrap5Asset::class],
		'notes'      => 'Asset for DataTables RowGroup',
	],
	\p2m\assets\datatables\P2DataTablesRowReorderAsset::class => [
		'name'       => 'P2DataTablesRowReorder',
		'type'       => 'cdn',
		'version'    => '1.5.0',
		'baseUrl'    => 'https://cdn.datatables.net/rowreorder/{version}',
		'css'        => ['css/rowReorder.bootstrap5.min.css'],
		'js'         => ['js/dataTables.rowReorder.min.js'],
		'deps'       => [\p2m\assets\datatables\P2DataTablesBootstrap5Asset::class],
		'notes'      => 'Asset for DataTables RowReorder',
	],
	\p2m\assets\datatables\P2DataTablesScrollerAsset::class => [
		'name'       => 'P2DataTablesScroller',
		'type'       => 'cdn',
		'version'    => '2.4.3',
		'baseUrl'    => 'https://cdn.datatables.net/scroller/{version}',
		'css'        => ['css/scroller.bootstrap5.min.css'],
		'js'         => ['js/dataTables.scroller.min.js'],
		'deps'       => [\p2m\assets\datatables\P2DataTablesBootstrap5Asset::class],
		'notes'      => 'Asset for DataTables Scroller',
	],
	\p2m\assets\datatables\P2DataTablesSearchBuilderAsset::class => [
		'name'       => 'P2DataTablesSearchBuilder',
		'type'       => 'cdn',
		'version'    => '1.8.2',
		'baseUrl'    => 'https://cdn.datatables.net/searchbuilder/{version}',
		'css'        => [],
		'js'         => ['js/searchBuilder.bootstrap5.min.js'],
		'deps'       => [\p2m\assets\base\P2DataTablesSearchBuilderBaseAsset::class],
		'notes'      => 'Asset for DataTables SearchBuilder',
	],
	\p2m\assets\datatables\P2DataTablesSearchPanesAsset::class => [
		'name'       => 'P2DataTablesSearchPanes',
		'type'       => 'cdn',
		'version'    => '2.3.3',
		'baseUrl'    => 'https://cdn.datatables.net/searchpanes/{version}',
		'css'        => [],
		'js'         => ['js/searchPanes.bootstrap5.min.js'],
		'deps'       => [\p2m\assets\base\P2DataTablesSearchPanesBaseAsset::class],
		'notes'      => 'Asset for DataTables SearchPanes',
	],
	\p2m\assets\datatables\P2DataTablesSelectAsset::class => [
		'name'       => 'P2DataTablesSelect',
		'type'       => 'cdn',
		'version'    => '3.0.0',
		'baseUrl'    => 'https://cdn.datatables.net/select/{version}',
		'css'        => ['css/select.bootstrap5.min.css'],
		'js'         => ['js/dataTables.select.min.js'],
		'deps'       => [\p2m\assets\datatables\P2DataTablesBootstrap5Asset::class],
		'notes'      => 'Asset for DataTables Select',
	],
	\p2m\assets\datatables\P2DataTablesStateRestoreAsset::class => [
		'name'       => 'P2DataTablesStateRestore',
		'type'       => 'cdn',
		'version'    => '1.4.1',
		'baseUrl'    => 'https://cdn.datatables.net/staterestore/{version}',
		'css'        => [],
		'js'         => ['js/stateRestore.bootstrap5.min.js'],
		'deps'       => [\p2m\assets\base\P2DataTablesStateRestoreBaseAsset::class],
		'notes'      => 'Asset for DataTables StateRestore',
	],
	/**
	 * -- -- ^ -- -- ^ -- -- ^ -- -- ^ -- -- ^ -- -- ^ -- -- ^ -- -- ^ -- --
	 *                       FullCalendar assets
	 * -- -- ^ -- -- ^ -- -- ^ -- -- ^ -- -- ^ -- -- ^ -- -- ^ -- -- ^ -- --
	 */
	\p2m\assets\fullcalendar\P2FullCalendarBootstrap5Asset::class => [
		'name'       => 'P2FullCalendarBootstrap5',
		'type'       => 'cdn',
		'version'    => '6.1.15',
		'baseUrl'    => 'https://cdn.jsdelivr.net/npm/@fullcalendar/bootstrap5@{version}',
		'css'        => [],
		'js'         => ['index.global.min.js'],
		'deps'       => [\p2m\assets\base\P2FullCalendarBaseAsset::class],
		'notes'      => 'Asset for FullCalendar Bootstrap5',
	],
	\p2m\assets\fullcalendar\P2FullCalendarDaygridAsset::class => [
		'name'       => 'P2FullCalendarDaygrid',
		'type'       => 'cdn',
		'version'    => '6.1.15',
		'baseUrl'    => 'https://cdn.jsdelivr.net/npm/@fullcalendar/daygrid@{version}',
		'css'        => [],
		'js'         => ['index.global.min.js'],
		'deps'       => [\p2m\assets\fullcalendar\P2FullCalendarBootstrap5Asset::class],
		'notes'      => 'Asset for FullCalendar Daygrid',
	],
	\p2m\assets\fullcalendar\P2FullCalendarGoogleCalendarAsset::class => [
		'name'       => 'P2FullCalendarGoogleCalendar',
		'type'       => 'cdn',
		'version'    => '6.1.15',
		'baseUrl'    => 'https://cdn.jsdelivr.net/npm/@fullcalendar/google-calendar@{version}',
		'css'        => [],
		'js'         => ['index.global.min.js'],
		'deps'       => [\p2m\assets\fullcalendar\P2FullCalendarBootstrap5Asset::class],
		'notes'      => 'Asset for FullCalendar GoogleCalendar',
	],
	\p2m\assets\fullcalendar\P2FullCalendarIcalendarAsset::class => [
		'name'       => 'P2FullCalendarIcalendar',
		'type'       => 'cdn',
		'version'    => '6.1.15',
		'baseUrl'    => 'https://cdn.jsdelivr.net/npm/@fullcalendar/icalendar@{version}',
		'css'        => [],
		'js'         => ['index.global.min.js'],
		'deps'       => [\p2m\assets\fullcalendar\P2FullCalendarBootstrap5Asset::class],
		'notes'      => 'Asset for FullCalendar Icalendar',
	],
	\p2m\assets\fullcalendar\P2FullCalendarInteractionAsset::class => [
		'name'       => 'P2FullCalendarInteraction',
		'type'       => 'cdn',
		'version'    => '6.1.15',
		'baseUrl'    => 'https://cdn.jsdelivr.net/npm/@fullcalendar/interaction@{version}',
		'css'        => [],
		'js'         => ['index.global.min.js'],
		'deps'       => [\p2m\assets\fullcalendar\P2FullCalendarBootstrap5Asset::class],
		'notes'      => 'Asset for FullCalendar Interaction',
	],
	\p2m\assets\fullcalendar\P2FullCalendarListAsset::class => [
		'name'       => 'P2FullCalendarList',
		'type'       => 'cdn',
		'version'    => '6.1.15',
		'baseUrl'    => 'https://cdn.jsdelivr.net/npm/@fullcalendar/list@{version}',
		'css'        => [],
		'js'         => ['index.global.min.js'],
		'deps'       => [\p2m\assets\fullcalendar\P2FullCalendarBootstrap5Asset::class],
		'notes'      => 'Asset for FullCalendar List',
	],
	\p2m\assets\fullcalendar\P2FullCalendarMomentAsset::class => [
		'name'       => 'P2FullCalendarMoment',
		'type'       => 'cdn',
		'version'    => '6.1.15',
		'baseUrl'    => 'https://cdn.jsdelivr.net/npm/@fullcalendar/moment@{version}',
		'css'        => [],
		'js'         => ['index.global.min.js'],
		'deps'       => [\p2m\assets\fullcalendar\P2FullCalendarBootstrap5Asset::class],
		'notes'      => 'Asset for FullCalendar Moment',
	],
	\p2m\assets\fullcalendar\P2FullCalendarMomentTimezoneAsset::class => [
		'name'       => 'P2FullCalendarMomentTimezone',
		'type'       => 'cdn',
		'version'    => '6.1.15',
		'baseUrl'    => 'https://cdn.jsdelivr.net/npm/@fullcalendar/moment-timezone@{version}',
		'css'        => [],
		'js'         => ['index.global.min.js'],
		'deps'       => [\p2m\assets\fullcalendar\P2FullCalendarBootstrap5Asset::class],
		'notes'      => 'Asset for FullCalendar MomentTimezone',
	],
	\p2m\assets\fullcalendar\P2FullCalendarMultimonthAsset::class => [
		'name'       => 'P2FullCalendarMultimonth',
		'type'       => 'cdn',
		'version'    => '6.1.15',
		'baseUrl'    => 'https://cdn.jsdelivr.net/npm/@fullcalendar/multimonth@{version}',
		'css'        => [],
		'js'         => ['index.global.min.js'],
		'deps'       => [\p2m\assets\fullcalendar\P2FullCalendarBootstrap5Asset::class],
		'notes'      => 'Asset for FullCalendar Multimonth',
	],
	\p2m\assets\fullcalendar\P2FullCalendarScrollgridAsset::class => [
		'name'       => 'P2FullCalendarScrollgrid',
		'type'       => 'cdn',
		'version'    => '6.1.15',
		'baseUrl'    => 'https://cdn.jsdelivr.net/npm/@fullcalendar/scrollgrid@{version}',
		'css'        => ['index.global.min.js'],
		'js'         => ['_source_min_js_'],
		'deps'       => [\p2m\assets\fullcalendar\P2FullCalendarBootstrap5Asset::class],
		'notes'      => 'Asset for FullCalendar Scrollgrid',
	],
	\p2m\assets\fullcalendar\P2FullCalendarTimegridAsset::class => [
		'name'       => 'P2FullCalendarTimegrid',
		'type'       => 'cdn',
		'version'    => '6.1.15',
		'baseUrl'    => 'https://cdn.jsdelivr.net/npm/@fullcalendar/timegrid@{version}',
		'css'        => [],
		'js'         => ['index.global.min.js'],
		'deps'       => [\p2m\assets\fullcalendar\P2FullCalendarBootstrap5Asset::class],
		'notes'      => 'Asset for FullCalendar Timegrid',
	],
];
