<?php
/**
 * P2FlagIconFactory.php
 *
 * @author Pedro Plowman
 * @copyright Copyright &copy; Pedro Plowman, 2025
 * @link https://github.com/p2made
 * @license MIT
 */

/**
 * @class \p2m\internal\helpers\P2FlagIconFactory
 * @package p2made/p2y2-things
 */

/**
 * @internal
 * Not part of the public API. Subject to change without notice.
 */

namespace p2m\internal\helpers;

class P2FlagIconFactory extends P2IconFactory
{
	/**
	 * flags name
	 */

	// Unknown/xx is used as fallback

	public const _XX = 'xx';                  // Unknown
	public const _UNKNOWN = 'xx';

	// Africa

	public const _DZ = 'dz';                  // Algeria
	public const _ALGERIA = 'dz';
	public const _AO = 'ao';                  // Angola
	public const _ANGOLA = 'ao';
	public const _SH_AC = 'sh-ac';            // Ascension Island
	public const _ASCENSION_ISLAND = 'sh-ac';
	public const _BJ = 'bj';                  // Benin
	public const _BENIN = 'bj';
	public const _BW = 'bw';                  // Botswana
	public const _BOTSWANA = 'bw';
	public const _BF = 'bf';                  // Burkina Faso
	public const _BURKINA_FASO = 'bf';
	public const _BI = 'bi';                  // Burundi
	public const _BURUNDI = 'bi';
	public const _CV = 'cv';                  // Cabo Verde
	public const _CABO_VERDE = 'cv';
	public const _CM = 'cm';                  // Cameroon
	public const _CAMEROON = 'cm';
	public const _CF = 'cf';                  // Central African Republic
	public const _CENTRAL_AFRICAN_REPUBLIC = 'cf';
	public const _TD = 'td';                  // Chad
	public const _CHAD = 'td';
	public const _KM = 'km';                  // Comoros
	public const _COMOROS = 'km';
	public const _CI = 'ci';                  // Côte d'Ivoire
	public const _COTE_DIVOIRE = 'ci';
	public const _CD = 'cd';                  // Democratic Republic of the Congo
	public const _DEMOCRATIC_REPUBLIC_OF_THE_CONGO = 'cd';
	public const _DJ = 'dj';                  // Djibouti
	public const _DJIBOUTI = 'dj';
	public const _EG = 'eg';                  // Egypt
	public const _EGYPT = 'eg';
	public const _GQ = 'gq';                  // Equatorial Guinea
	public const _EQUATORIAL_GUINEA = 'gq';
	public const _ER = 'er';                  // Eritrea
	public const _ERITREA = 'er';
	public const _SZ = 'sz';                  // Eswatini
	public const _ESWATINI = 'sz';
	public const _ET = 'et';                  // Ethiopia
	public const _ETHIOPIA = 'et';
	public const _TF = 'tf';                  // French Southern Territories
	public const _FRENCH_SOUTHERN_TERRITORIES = 'tf';
	public const _GA = 'ga';                  // Gabon
	public const _GABON = 'ga';
	public const _GM = 'gm';                  // Gambia
	public const _GAMBIA = 'gm';
	public const _GH = 'gh';                  // Ghana
	public const _GHANA = 'gh';
	public const _GN = 'gn';                  // Guinea
	public const _GUINEA = 'gn';
	public const _GW = 'gw';                  // Guinea-Bissau
	public const _GUINEA_BISSAU = 'gw';
	public const _KE = 'ke';                  // Kenya
	public const _KENYA = 'ke';
	public const _LS = 'ls';                  // Lesotho
	public const _LESOTHO = 'ls';
	public const _LR = 'lr';                  // Liberia
	public const _LIBERIA = 'lr';
	public const _LY = 'ly';                  // Libya
	public const _LIBYA = 'ly';
	public const _MG = 'mg';                  // Madagascar
	public const _MADAGASCAR = 'mg';
	public const _MW = 'mw';                  // Malawi
	public const _MALAWI = 'mw';
	public const _ML = 'ml';                  // Mali
	public const _MALI = 'ml';
	public const _MR = 'mr';                  // Mauritania
	public const _MAURITANIA = 'mr';
	public const _MU = 'mu';                  // Mauritius
	public const _MAURITIUS = 'mu';
	public const _YT = 'yt';                  // Mayotte
	public const _MAYOTTE = 'yt';
	public const _MA = 'ma';                  // Morocco
	public const _MOROCCO = 'ma';
	public const _MZ = 'mz';                  // Mozambique
	public const _MOZAMBIQUE = 'mz';
	public const _NA = 'na';                  // Namibia
	public const _NAMIBIA = 'na';
	public const _NE = 'ne';                  // Niger
	public const _NIGER = 'ne';
	public const _NG = 'ng';                  // Nigeria
	public const _NIGERIA = 'ng';
	public const _CG = 'cg';                  // Republic of the Congo
	public const _REPUBLIC_OF_THE_CONGO = 'cg';
	public const _RW = 'rw';                  // Rwanda
	public const _RWANDA = 'rw';
	public const _RE = 're';                  // Réunion
	public const _REUNION = 're';
	public const _SH_HL = 'sh-hl';            // Saint Helena
	public const _SAINT_HELENA = 'sh-hl';
	public const _SH = 'sh';                  // Saint Helena, Ascension and Tristan da Cunha
	public const _SAINT_HELENA_ASCENSION_TRISTAN_DA_CUNHA = 'sh';
	public const _ST = 'st';                  // Sao Tome and Principe
	public const _SAO_TOME_PRINCIPE = 'st';
	public const _SN = 'sn';                  // Senegal
	public const _SENEGAL = 'sn';
	public const _SC = 'sc';                  // Seychelles
	public const _SEYCHELLES = 'sc';
	public const _SL = 'sl';                  // Sierra Leone
	public const _SIERRA_LEONE = 'sl';
	public const _SO = 'so';                  // Somalia
	public const _SOMALIA = 'so';
	public const _ZA = 'za';                  // South Africa
	public const _SOUTH_AFRICA = 'za';
	public const _SS = 'ss';                  // South Sudan
	public const _SOUTH_SUDAN = 'ss';
	public const _SD = 'sd';                  // Sudan
	public const _SUDAN = 'sd';
	public const _TZ = 'tz';                  // Tanzania
	public const _TANZANIA = 'tz';
	public const _TG = 'tg';                  // Togo
	public const _TOGO = 'tg';
	public const _SH_TA = 'sh-ta';            // Tristan da Cunha
	public const _TRISTAN_DA_CUNHA = 'sh-ta';
	public const _TN = 'tn';                  // Tunisia
	public const _TUNISIA = 'tn';
	public const _UG = 'ug';                  // Uganda
	public const _UGANDA = 'ug';
	public const _EH = 'eh';                  // Western Sahara
	public const _WESTERN_SAHARA = 'eh';
	public const _ZM = 'zm';                  // Zambia
	public const _ZAMBIA = 'zm';
	public const _ZW = 'zw';                  // Zimbabwe
	public const _ZIMBABWE = 'zw';

	// Antarctica

	public const _AQ = 'aq';                  // Antarctica
	public const _ANTARCTICA = 'aq';
	public const _GS = 'gs';                  // South Georgia and the South Sandwich Islands
	public const _SOUTH_GEORGIA_THE_SOUTH_SANDWICH_ISLANDS = 'gs';

	// Asia

	public const _AF = 'af';                  // Afghanistan
	public const _AFGHANISTAN = 'af';
	public const _RU_AGB = 'ru-agb';          // Agin-Buryat Okrug
	public const _AGIN_BURYAT_OKRUG = 'ru-agb';
	public const _RU_AL = 'ru-al';            // Altai Republic
	public const _ALTAI_REPUBLIC = 'ru-al';
	public const _AM = 'am';                  // Armenia
	public const _ARMENIA = 'am';
	public const _AZ = 'az';                  // Azerbaijan
	public const _AZERBAIJAN = 'az';
	public const _BH = 'bh';                  // Bahrain
	public const _BAHRAIN = 'bh';
	public const _BD = 'bd';                  // Bangladesh
	public const _BANGLADESH = 'bd';
	public const _BT = 'bt';                  // Bhutan
	public const _BHUTAN = 'bt';
	public const _IO = 'io';                  // British Indian Ocean Territory
	public const _BRITISH_INDIAN_OCEAN_TERRITORY = 'io';
	public const _BN = 'bn';                  // Brunei Darussalam
	public const _BRUNEI_DARUSSALAM = 'bn';
	public const _RU_BU = 'ru-bu';            // Buryatia
	public const _BURYATIA = 'ru-bu';
	public const _KH = 'kh';                  // Cambodia
	public const _CAMBODIA = 'kh';
	public const _RU_CHE = 'ru-che';          // Chelyabinsk Oblast
	public const _CHELYABINSK_OBLAST = 'ru-che';
	public const _CN = 'cn';                  // China
	public const _CHINA = 'cn';
	public const _CX = 'cx';                  // Christmas Island
	public const _CHRISTMAS_ISLAND = 'cx';
	public const _RU_CHU = 'ru-chu';          // Chukotka Autonomous Okrug
	public const _CHUKOTKA_AUTONOMOUS_OKRUG = 'ru-chu';
	public const _CC = 'cc';                  // Cocos (Keeling) Islands
	public const _COCOS_KEELING_ISLANDS = 'cc';
	public const _CN_ET = 'cn-et';            // East Turkestan
	public const _EAST_TURKESTAN = 'cn-et';
	public const _GE = 'ge';                  // Georgia
	public const _GEORGIA = 'ge';
	public const _HAZST = 'hazst';            // Hazaristan
	public const _HAZARISTAN = 'hazst';
	public const _HK = 'hk';                  // Hong Kong
	public const _HONG_KONG = 'hk';
	public const _IN = 'in';                  // India
	public const _INDIA = 'in';
	public const _ID = 'id';                  // Indonesia
	public const _INDONESIA = 'id';
	public const _IR = 'ir';                  // Iran
	public const _IRAN = 'ir';
	public const _IQ = 'iq';                  // Iraq
	public const _IRAQ = 'iq';
	public const _RU_IRK = 'ru-irk';          // Irkutsk Oblast
	public const _IRKUTSK_OBLAST = 'ru-irk';
	public const _IL = 'il';                  // Israel
	public const _ISRAEL = 'il';
	public const _JP = 'jp';                  // Japan
	public const _JAPAN = 'jp';
	public const _RU_YEV = 'ru-yev';          // Jewish Autonomous Oblast
	public const _JEWISH_AUTONOMOUS_OBLAST = 'ru-yev';
	public const _JO = 'jo';                  // Jordan
	public const _JORDAN = 'jo';
	public const _KZ = 'kz';                  // Kazakhstan
	public const _KAZAKHSTAN = 'kz';
	public const _RU_KHA = 'ru-kha';          // Khabarovsk Krai
	public const _KHABAROVSK_KRAI = 'ru-kha';
	public const _RU_KK = 'ru-kk';            // Khakassia
	public const _KHAKASSIA = 'ru-kk';
	public const _RU_KYA = 'ru-kya';          // Krasnoyarsk Krai
	public const _KRASNOYARSK_KRAI = 'ru-kya';
	public const _RU_KGN = 'ru-kgn';          // Kurgan Oblast
	public const _KURGAN_OBLAST = 'ru-kgn';
	public const _KW = 'kw';                  // Kuwait
	public const _KUWAIT = 'kw';
	public const _KG = 'kg';                  // Kyrgyzstan
	public const _KYRGYZSTAN = 'kg';
	public const _LA = 'la';                  // Laos
	public const _LAOS = 'la';
	public const _LB = 'lb';                  // Lebanon
	public const _LEBANON = 'lb';
	public const _MO = 'mo';                  // Macau
	public const _MACAU = 'mo';
	public const _MY = 'my';                  // Malaysia
	public const _MALAYSIA = 'my';
	public const _MV = 'mv';                  // Maldives
	public const _MALDIVES = 'mv';
	public const _MN = 'mn';                  // Mongolia
	public const _MONGOLIA = 'mn';
	public const _MM = 'mm';                  // Myanmar
	public const _MYANMAR = 'mm';
	public const _NP = 'np';                  // Nepal
	public const _NEPAL = 'np';
	public const _KP = 'kp';                  // North Korea
	public const _NORTH_KOREA = 'kp';
	public const _RU_NVS = 'ru-nvs';          // Novosibirsk Oblast
	public const _NOVOSIBIRSK_OBLAST = 'ru-nvs';
	public const _OM = 'om';                  // Oman
	public const _OMAN = 'om';
	public const _PK = 'pk';                  // Pakistan
	public const _PAKISTAN = 'pk';
	public const _PH = 'ph';                  // Philippines
	public const _PHILIPPINES = 'ph';
	public const _QA = 'qa';                  // Qatar
	public const _QATAR = 'qa';
	public const _RU_SA = 'ru-sa';            // Sakha Republic (Yakutia)
	public const _SAKHA_REPUBLIC_YAKUTIA = 'ru-sa';
	public const _RU_SAK = 'ru-sak';          // Sakhalin Oblast
	public const _SAKHALIN_OBLAST = 'ru-sak';
	public const _SA = 'sa';                  // Saudi Arabia
	public const _SAUDI_ARABIA = 'sa';
	public const _SG = 'sg';                  // Singapore
	public const _SINGAPORE = 'sg';
	public const _KR = 'kr';                  // South Korea
	public const _SOUTH_KOREA = 'kr';
	public const _LK = 'lk';                  // Sri Lanka
	public const _SRI_LANKA = 'lk';
	public const _PS = 'ps';                  // State of Palestine
	public const _STATE_OF_PALESTINE = 'ps';
	public const _RU_SVE = 'ru-sve';          // Sverdlovsk Oblast
	public const _SVERDLOVSK_OBLAST = 'ru-sve';
	public const _SY = 'sy';                  // Syria
	public const _SYRIA = 'sy';
	public const _TW = 'tw';                  // Taiwan
	public const _TAIWAN = 'tw';
	public const _TJ = 'tj';                  // Tajikistan
	public const _TAJIKISTAN = 'tj';
	public const _RU_TDN = 'ru-tdn';          // Taymyrsky Dolgano-Nenetsky District
	public const _TAYMYRSKY_DOLGANO_NENETSKY_DISTRICT = 'ru-tdn';
	public const _TH = 'th';                  // Thailand
	public const _THAILAND = 'th';
	public const _TL = 'tl';                  // Timor-Leste
	public const _TIMOR_LESTE = 'tl';
	public const _RU_TOM = 'ru-tom';          // Tomsk Oblast
	public const _TOMSK_OBLAST = 'ru-tom';
	public const _TM = 'tm';                  // Turkmenistan
	public const _TURKMENISTAN = 'tm';
	public const _RU_TY = 'ru-ty';            // Tuva
	public const _TUVA = 'ru-ty';
	public const _TR = 'tr';                  // Türkiye
	public const _TURKIYE = 'tr';
	public const _AE = 'ae';                  // United Arab Emirates
	public const _UNITED_ARAB_EMIRATES = 'ae';
	public const _UZ = 'uz';                  // Uzbekistan
	public const _UZBEKISTAN = 'uz';
	public const _VN = 'vn';                  // Vietnam
	public const _VIETNAM = 'vn';
	public const _YE = 'ye';                  // Yemen
	public const _YEMEN = 'ye';
	public const _RU_ZAB = 'ru-zab';          // Zabaykalsky Krai
	public const _ZABAYKALSKY_KRAI = 'ru-zab';

	// Europe

	public const _RU_AD = 'ru-ad';            // Adygea
	public const _ADYGEA = 'ru-ad';
	public const _AX = 'ax';                  // Aland Islands
	public const _ALAND_ISLANDS = 'ax';
	public const _AL = 'al';                  // Albania
	public const _ALBANIA = 'al';
	public const _AD = 'ad';                  // Andorra
	public const _ANDORRA = 'ad';
	public const _RU_ARK = 'ru-ark';          // Arkhangelsk Oblast
	public const _ARKHANGELSK_OBLAST = 'ru-ark';
	public const _RU_AST = 'ru-ast';          // Astrakhan Oblast
	public const _ASTRAKHAN_OBLAST = 'ru-ast';
	public const _AT = 'at';                  // Austria
	public const _AUSTRIA = 'at';
	public const _UA_43 = 'ua-43';            // Autonomous Republic of Crimea
	public const _AUTONOMOUS_REPUBLIC_OF_CRIMEA = 'ua-43';
	public const _PT_20 = 'pt-20';            // Azores
	public const _AZORES = 'pt-20';
	public const _ES_IB = 'es-ib';            // Balearic Islands
	public const _BALEARIC_ISLANDS = 'es-ib';
	public const _RU_BA = 'ru-ba';            // Bashkortostan
	public const _BASHKORTOSTAN = 'ru-ba';
	public const _ES_PV = 'es-pv';            // Basque Country
	public const _BASQUE_COUNTRY = 'es-pv';
	public const _BY = 'by';                  // Belarus
	public const _BELARUS = 'by';
	public const _BE = 'be';                  // Belgium
	public const _BELGIUM = 'be';
	public const _BA = 'ba';                  // Bosnia and Herzegovina
	public const _BOSNIA_HERZEGOVINA = 'ba';
	public const _RU_BRY = 'ru-bry';          // Bryansk Oblast
	public const _BRYANSK_OBLAST = 'ru-bry';
	public const _BG = 'bg';                  // Bulgaria
	public const _BULGARIA = 'bg';
	public const _IC = 'ic';                  // Canary Islands
	public const _CANARY_ISLANDS = 'ic';
	public const _ES_CT = 'es-ct';            // Catalonia
	public const _CATALONIA = 'es-ct';
	public const _RU_CE = 'ru-ce';            // Chechnya
	public const _CHECHNYA = 'ru-ce';
	public const _RU_CU = 'ru-cu';            // Chuvashia
	public const _CHUVASHIA = 'ru-cu';
	public const _HR = 'hr';                  // Croatia
	public const _CROATIA = 'hr';
	public const _CY = 'cy';                  // Cyprus
	public const _CYPRUS = 'cy';
	public const _CZ = 'cz';                  // Czech Republic
	public const _CZECH_REPUBLIC = 'cz';
	public const _RU_DA = 'ru-da';            // Dagestan
	public const _DAGESTAN = 'ru-da';
	public const _DK = 'dk';                  // Denmark
	public const _DENMARK = 'dk';
	public const _UA_14 = 'ua-14';            // Donetsk Oblast
	public const _DONETSK_OBLAST = 'ua-14';
	public const _GB_ENG = 'gb-eng';          // England
	public const _ENGLAND = 'gb-eng';
	public const _EE = 'ee';                  // Estonia
	public const _ESTONIA = 'ee';
	public const _FO = 'fo';                  // Faroe Islands
	public const _FAROE_ISLANDS = 'fo';
	public const _FI = 'fi';                  // Finland
	public const _FINLAND = 'fi';
	public const _FR = 'fr';                  // France
	public const _FRANCE = 'fr';
	public const _ES_GA = 'es-ga';            // Galicia
	public const _GALICIA = 'es-ga';
	public const _DE = 'de';                  // Germany
	public const _GERMANY = 'de';
	public const _GI = 'gi';                  // Gibraltar
	public const _GIBRALTAR = 'gi';
	public const _GR = 'gr';                  // Greece
	public const _GREECE = 'gr';
	public const _GG = 'gg';                  // Guernsey
	public const _GUERNSEY = 'gg';
	public const _VA = 'va';                  // Holy See
	public const _HOLY_SEE = 'va';
	public const _HU = 'hu';                  // Hungary
	public const _HUNGARY = 'hu';
	public const _IS = 'is';                  // Iceland
	public const _ICELAND = 'is';
	public const _RU_IN = 'ru-in';            // Ingushetia
	public const _INGUSHETIA = 'ru-in';
	public const _IE = 'ie';                  // Ireland
	public const _IRELAND = 'ie';
	public const _IM = 'im';                  // Isle of Man
	public const _ISLE_OF_MAN = 'im';
	public const _IT = 'it';                  // Italy
	public const _ITALY = 'it';
	public const _JE = 'je';                  // Jersey
	public const _JERSEY = 'je';
	public const _RU_KB = 'ru-kb';            // Kabardino-Balkaria
	public const _KABARDINO_BALKARIA = 'ru-kb';
	public const _RU_KGD = 'ru-kgd';          // Kaliningrad Oblast
	public const _KALININGRAD_OBLAST = 'ru-kgd';
	public const _RU_KL = 'ru-kl';            // Kalmykia
	public const _KALMYKIA = 'ru-kl';
	public const _RU_KLU = 'ru-klu';          // Kaluga Oblast
	public const _KALUGA_OBLAST = 'ru-klu';
	public const _RU_KC = 'ru-kc';            // Karachay-Cherkessia
	public const _KARACHAY_CHERKESSIA = 'ru-kc';
	public const _UZ_QR = 'uz-qr';            // Karakalpakstan
	public const _KARAKALPAKSTAN = 'uz-qr';
	public const _RU_KIR = 'ru-kir';          // Kirov Oblast
	public const _KIROV_OBLAST = 'ru-kir';
	public const _RU_KO = 'ru-ko';            // Komi Republic
	public const _KOMI_REPUBLIC = 'ru-ko';
	public const _XK = 'xk';                  // Kosovo
	public const _KOSOVO = 'xk';
	public const _RU_KOS = 'ru-kos';          // Kostroma Oblast
	public const _KOSTROMA_OBLAST = 'ru-kos';
	public const _RU_KDA = 'ru-kda';          // Krasnodar Krai
	public const _KRASNODAR_KRAI = 'ru-kda';
	public const _KPR = 'kpr';                // Kuban People's Republic
	public const _KUBAN_PEOPLES_REPUBLIC = 'kpr';
	public const _RU_KRS = 'ru-krs';          // Kursk Oblast
	public const _KURSK_OBLAST = 'ru-krs';
	public const _LV = 'lv';                  // Latvia
	public const _LATVIA = 'lv';
	public const _LI = 'li';                  // Liechtenstein
	public const _LIECHTENSTEIN = 'li';
	public const _LT = 'lt';                  // Lithuania
	public const _LITHUANIA = 'lt';
	public const _UA_09 = 'ua-09';            // Luhansk Oblast
	public const _LUHANSK_OBLAST = 'ua-09';
	public const _LU = 'lu';                  // Luxembourg
	public const _LUXEMBOURG = 'lu';
	public const _PT_30 = 'pt-30';            // Madeira
	public const _MADEIRA = 'pt-30';
	public const _MT = 'mt';                  // Malta
	public const _MALTA = 'mt';
	public const _MD = 'md';                  // Moldova
	public const _MOLDOVA = 'md';
	public const _MC = 'mc';                  // Monaco
	public const _MONACO = 'mc';
	public const _ME = 'me';                  // Montenegro
	public const _MONTENEGRO = 'me';
	public const _RU_MO = 'ru-mo';            // Mordovia
	public const _MORDOVIA = 'ru-mo';
	public const _RU_MOW = 'ru-mow';          // Moscow
	public const _MOSCOW = 'ru-mow';
	public const _RU_MOS = 'ru-mos';          // Moscow Oblast
	public const _MOSCOW_OBLAST = 'ru-mos';
	public const _RU_MUR = 'ru-mur';          // Murmansk Oblast
	public const _MURMANSK_OBLAST = 'ru-mur';
	public const _ES_NA = 'es-na';            // Navarra
	public const _NAVARRA = 'es-na';
	public const _NL = 'nl';                  // Netherlands
	public const _NETHERLANDS = 'nl';
	public const _RU_NIZ = 'ru-niz';          // Nizhny Novgorod Oblast
	public const _NIZHNY_NOVGOROD_OBLAST = 'ru-niz';
	public const _MK = 'mk';                  // North Macedonia
	public const _NORTH_MACEDONIA = 'mk';
	public const _RU_SE = 'ru-se';            // North Ossetia–Alania
	public const _NORTH_OSSETIAALANIA = 'ru-se';
	public const _GB_NIR = 'gb-nir';          // Northern Ireland
	public const _NORTHERN_IRELAND = 'gb-nir';
	public const _NO = 'no';                  // Norway
	public const _NORWAY = 'no';
	public const _RU_NGR = 'ru-ngr';          // Novgorod Oblast
	public const _NOVGOROD_OBLAST = 'ru-ngr';
	public const _RU_ORE = 'ru-ore';          // Orenburg Oblast
	public const _ORENBURG_OBLAST = 'ru-ore';
	public const _RU_ORL = 'ru-orl';          // Oryol Oblast
	public const _ORYOL_OBLAST = 'ru-orl';
	public const _RU_PNZ = 'ru-pnz';          // Penza Oblast
	public const _PENZA_OBLAST = 'ru-pnz';
	public const _RU_PER = 'ru-per';          // Perm Krai
	public const _PERM_KRAI = 'ru-per';
	public const _PL = 'pl';                  // Poland
	public const _POLAND = 'pl';
	public const _PT = 'pt';                  // Portugal
	public const _PORTUGAL = 'pt';
	public const _RU_KR = 'ru-kr';            // Republic of Karelia
	public const _REPUBLIC_OF_KARELIA = 'ru-kr';
	public const _RO = 'ro';                  // Romania
	public const _ROMANIA = 'ro';
	public const _RU_ROS = 'ru-ros';          // Rostov Oblast
	public const _ROSTOV_OBLAST = 'ru-ros';
	public const _RU = 'ru';                  // Russia
	public const _RUSSIA = 'ru';
	public const _RU_RYA = 'ru-rya';          // Ryazan Oblast
	public const _RYAZAN_OBLAST = 'ru-rya';
	public const _RU_SPE = 'ru-spe';          // Saint Petersburg
	public const _SAINT_PETERSBURG = 'ru-spe';
	public const _RU_SAM = 'ru-sam';          // Samara Oblast
	public const _SAMARA_OBLAST = 'ru-sam';
	public const _SM = 'sm';                  // San Marino
	public const _SAN_MARINO = 'sm';
	public const _RU_SAR = 'ru-sar';          // Saratov Oblast
	public const _SARATOV_OBLAST = 'ru-sar';
	public const _GB_SCT = 'gb-sct';          // Scotland
	public const _SCOTLAND = 'gb-sct';
	public const _RS = 'rs';                  // Serbia
	public const _SERBIA = 'rs';
	public const _UA_SV = 'ua-sv';            // Sevastopol
	public const _SEVASTOPOL = 'ua-sv';
	public const _GB_ZET = 'gb-zet';          // Shetland
	public const _SHETLAND = 'gb-zet';
	public const _SK = 'sk';                  // Slovakia
	public const _SLOVAKIA = 'sk';
	public const _SI = 'si';                  // Slovenia
	public const _SLOVENIA = 'si';
	public const _ES = 'es';                  // Spain
	public const _SPAIN = 'es';
	public const _RU_STA = 'ru-sta';          // Stavropol Krai
	public const _STAVROPOL_KRAI = 'ru-sta';
	public const _SJ = 'sj';                  // Svalbard and Jan Mayen
	public const _SVALBARD_JAN_MAYEN = 'sj';
	public const _SE = 'se';                  // Sweden
	public const _SWEDEN = 'se';
	public const _CH = 'ch';                  // Switzerland
	public const _SWITZERLAND = 'ch';
	public const _RU_TAM = 'ru-tam';          // Tambov Oblast
	public const _TAMBOV_OBLAST = 'ru-tam';
	public const _RU_TA = 'ru-ta';            // Tatarstan
	public const _TATARSTAN = 'ru-ta';
	public const _RU_TUL = 'ru-tul';          // Tula Oblast
	public const _TULA_OBLAST = 'ru-tul';
	public const _RU_TVE = 'ru-tve';          // Tver Oblast
	public const _TVER_OBLAST = 'ru-tve';
	public const _RU_UD = 'ru-ud';            // Udmurtia
	public const _UDMURTIA = 'ru-ud';
	public const _UA = 'ua';                  // Ukraine
	public const _UKRAINE = 'ua';
	public const _RU_ULY = 'ru-uly';          // Ulyanovsk Oblast
	public const _ULYANOVSK_OBLAST = 'ru-uly';
	public const _GB = 'gb';                  // United Kingdom
	public const _UNITED_KINGDOM = 'gb';
	public const _UA_05 = 'ua-05';            // Vinnytsia Oblast
	public const _VINNYTSIA_OBLAST = 'ua-05';
	public const _UA_07 = 'ua-07';            // Volyn Oblast
	public const _VOLYN_OBLAST = 'ua-07';
	public const _GB_WLS = 'gb-wls';          // Wales
	public const _WALES = 'gb-wls';
	public const _RU_YAR = 'ru-yar';          // Yaroslavl Oblast
	public const _YAROSLAVL_OBLAST = 'ru-yar';
	public const _UA_21 = 'ua-21';            // Zakarpattia Oblast
	public const _ZAKARPATTIA_OBLAST = 'ua-21';
	public const _UA_23 = 'ua-23';            // Zaporizhzhia Oblast
	public const _ZAPORIZHZHIA_OBLAST = 'ua-23';
	public const _UA_18 = 'ua-18';            // Zhytomyr Oblast
	public const _ZHYTOMYR_OBLAST = 'ua-18';

	// North America

	public const _AI = 'ai';                  // Anguilla
	public const _ANGUILLA = 'ai';
	public const _AG = 'ag';                  // Antigua and Barbuda
	public const _ANTIGUA_BARBUDA = 'ag';
	public const _BS = 'bs';                  // Bahamas
	public const _BAHAMAS = 'bs';
	public const _BB = 'bb';                  // Barbados
	public const _BARBADOS = 'bb';
	public const _BZ = 'bz';                  // Belize
	public const _BELIZE = 'bz';
	public const _BM = 'bm';                  // Bermuda
	public const _BERMUDA = 'bm';
	public const _CA = 'ca';                  // Canada
	public const _CANADA = 'ca';
	public const _KY = 'ky';                  // Cayman Islands
	public const _CAYMAN_ISLANDS = 'ky';
	public const _CR = 'cr';                  // Costa Rica
	public const _COSTA_RICA = 'cr';
	public const _CU = 'cu';                  // Cuba
	public const _CUBA = 'cu';
	public const _DM = 'dm';                  // Dominica
	public const _DOMINICA = 'dm';
	public const _DO = 'do';                  // Dominican Republic
	public const _DOMINICAN_REPUBLIC = 'do';
	public const _SV = 'sv';                  // El Salvador
	public const _EL_SALVADOR = 'sv';
	public const _GL = 'gl';                  // Greenland
	public const _GREENLAND = 'gl';
	public const _GD = 'gd';                  // Grenada
	public const _GRENADA = 'gd';
	public const _GP = 'gp';                  // Guadeloupe
	public const _GUADELOUPE = 'gp';
	public const _GT = 'gt';                  // Guatemala
	public const _GUATEMALA = 'gt';
	public const _HT = 'ht';                  // Haiti
	public const _HAITI = 'ht';
	public const _HN = 'hn';                  // Honduras
	public const _HONDURAS = 'hn';
	public const _JM = 'jm';                  // Jamaica
	public const _JAMAICA = 'jm';
	public const _MQ = 'mq';                  // Martinique
	public const _MARTINIQUE = 'mq';
	public const _MX = 'mx';                  // Mexico
	public const _MEXICO = 'mx';
	public const _MS = 'ms';                  // Montserrat
	public const _MONTSERRAT = 'ms';
	public const _NI = 'ni';                  // Nicaragua
	public const _NICARAGUA = 'ni';
	public const _PA = 'pa';                  // Panama
	public const _PANAMA = 'pa';
	public const _PR = 'pr';                  // Puerto Rico
	public const _PUERTO_RICO = 'pr';
	public const _BL = 'bl';                  // Saint Barthélemy
	public const _SAINT_BARTHELEMY = 'bl';
	public const _KN = 'kn';                  // Saint Kitts and Nevis
	public const _SAINT_KITTS_NEVIS = 'kn';
	public const _LC = 'lc';                  // Saint Lucia
	public const _SAINT_LUCIA = 'lc';
	public const _MF = 'mf';                  // Saint Martin
	public const _SAINT_MARTIN = 'mf';
	public const _PM = 'pm';                  // Saint Pierre and Miquelon
	public const _SAINT_PIERRE_MIQUELON = 'pm';
	public const _VC = 'vc';                  // Saint Vincent and the Grenadines
	public const _SAINT_VINCENT_THE_GRENADINES = 'vc';
	public const _SX = 'sx';                  // Sint Maarten
	public const _SINT_MAARTEN = 'sx';
	public const _TC = 'tc';                  // Turks and Caicos Islands
	public const _TURKS_CAICOS_ISLANDS = 'tc';
	public const _UM = 'um';                  // United States Minor Outlying Islands
	public const _UNITED_STATES_MINOR_OUTLYING_ISLANDS = 'um';
	public const _US = 'us';                  // United States of America
	public const _UNITED_STATES_OF_AMERICA = 'us';
	public const _VG = 'vg';                  // Virgin Islands (British)
	public const _VIRGIN_ISLANDS_BRITISH = 'vg';
	public const _VI = 'vi';                  // Virgin Islands (U.S.)
	public const _VIRGIN_ISLANDS_US = 'vi';

	// Oceania

	public const _AS = 'as';                  // American Samoa
	public const _AMERICAN_SAMOA = 'as';
	public const _AU = 'au';                  // Australia
	public const _AUSTRALIA = 'au';
	public const _BV = 'bv';                  // Bouvet Island
	public const _BOUVET_ISLAND = 'bv';
	public const _CP = 'cp';                  // Clipperton Island
	public const _CLIPPERTON_ISLAND = 'cp';
	public const _CK = 'ck';                  // Cook Islands
	public const _COOK_ISLANDS = 'ck';
	public const _DG = 'dg';                  // Diego Garcia
	public const _DIEGO_GARCIA = 'dg';
	public const _FM = 'fm';                  // Federated States of Micronesia
	public const _FEDERATED_STATES_OF_MICRONESIA = 'fm';
	public const _FJ = 'fj';                  // Fiji
	public const _FIJI = 'fj';
	public const _PF = 'pf';                  // French Polynesia
	public const _FRENCH_POLYNESIA = 'pf';
	public const _GU = 'gu';                  // Guam
	public const _GUAM = 'gu';
	public const _HM = 'hm';                  // Heard Island and McDonald Islands
	public const _HEARD_ISLAND_MCDONALD_ISLANDS = 'hm';
	public const _KI = 'ki';                  // Kiribati
	public const _KIRIBATI = 'ki';
	public const _MH = 'mh';                  // Marshall Islands
	public const _MARSHALL_ISLANDS = 'mh';
	public const _NR = 'nr';                  // Nauru
	public const _NAURU = 'nr';
	public const _NC = 'nc';                  // New Caledonia
	public const _NEW_CALEDONIA = 'nc';
	public const _NZ = 'nz';                  // New Zealand
	public const _NEW_ZEALAND = 'nz';
	public const _NU = 'nu';                  // Niue
	public const _NIUE = 'nu';
	public const _NF = 'nf';                  // Norfolk Island
	public const _NORFOLK_ISLAND = 'nf';
	public const _MP = 'mp';                  // Northern Mariana Islands
	public const _NORTHERN_MARIANA_ISLANDS = 'mp';
	public const _PW = 'pw';                  // Palau
	public const _PALAU = 'pw';
	public const _PG = 'pg';                  // Papua New Guinea
	public const _PAPUA_NEW_GUINEA = 'pg';
	public const _PN = 'pn';                  // Pitcairn
	public const _PITCAIRN = 'pn';
	public const _WS = 'ws';                  // Samoa
	public const _SAMOA = 'ws';
	public const _SB = 'sb';                  // Solomon Islands
	public const _SOLOMON_ISLANDS = 'sb';
	public const _TK = 'tk';                  // Tokelau
	public const _TOKELAU = 'tk';
	public const _TO = 'to';                  // Tonga
	public const _TONGA = 'to';
	public const _TV = 'tv';                  // Tuvalu
	public const _TUVALU = 'tv';
	public const _VU = 'vu';                  // Vanuatu
	public const _VANUATU = 'vu';
	public const _WF = 'wf';                  // Wallis and Futuna
	public const _WALLIS_FUTUNA = 'wf';

	// South America

	public const _AR = 'ar';                  // Argentina
	public const _ARGENTINA = 'ar';
	public const _AW = 'aw';                  // Aruba
	public const _ARUBA = 'aw';
	public const _BO = 'bo';                  // Bolivia
	public const _BOLIVIA = 'bo';
	public const _BQ = 'bq';                  // Bonaire, Sint Eustatius and Saba
	public const _BONAIRE_SINT_EUSTATIUS_SABA = 'bq';
	public const _BR = 'br';                  // Brazil
	public const _BRAZIL = 'br';
	public const _CL = 'cl';                  // Chile
	public const _CHILE = 'cl';
	public const _CO = 'co';                  // Colombia
	public const _COLOMBIA = 'co';
	public const _CW = 'cw';                  // Curaçao
	public const _CURACAO = 'cw';
	public const _EC = 'ec';                  // Ecuador
	public const _ECUADOR = 'ec';
	public const _FK = 'fk';                  // Falkland Islands
	public const _FALKLAND_ISLANDS = 'fk';
	public const _GF = 'gf';                  // French Guiana
	public const _FRENCH_GUIANA = 'gf';
	public const _GY = 'gy';                  // Guyana
	public const _GUYANA = 'gy';
	public const _PY = 'py';                  // Paraguay
	public const _PARAGUAY = 'py';
	public const _PE = 'pe';                  // Peru
	public const _PERU = 'pe';
	public const _SR = 'sr';                  // Suriname
	public const _SURINAME = 'sr';
	public const _TT = 'tt';                  // Trinidad and Tobago
	public const _TRINIDAD_TOBAGO = 'tt';
	public const _UY = 'uy';                  // Uruguay
	public const _URUGUAY = 'uy';
	public const _VE = 've';                  // Venezuela
	public const _VENEZUELA = 've';

	// People

	public const _ABZ = 'abz';                // Abazins
	public const _ABAZINS = 'abz';
	public const _AU_AA = 'au-aa';            // Aboriginal Australians
	public const _ABORIGINAL_AUSTRALIANS = 'au-aa';
	public const _CHLM = 'chlm';              // Chulym
	public const _CHULYM = 'chlm';
	public const _CCSS = 'ccss';              // Circassians
	public const _CIRCASSIANS = 'ccss';
	public const _CR_TAT = 'cr-tat';          // Crimean Tatars
	public const _CRIMEAN_TATARS = 'cr-tat';
	public const _HAZ = 'haz';                // Hazarra
	public const _HAZARRA = 'haz';
	public const _KRCH = 'krch';              // Karachays
	public const _KARACHAYS = 'krch';
	public const _KKA = 'kka';                // Khakas
	public const _KHAKAS = 'kka';
	public const _NOG = 'nog';                // Nogais
	public const _NOGAIS = 'nog';
	public const _PAM = 'pam';                // Pamiris
	public const _PAMIRIS = 'pam';
	public const _AU_TSI = 'au-tsi';          // Torres Strait Islands
	public const _TORRES_STRAIT_ISLANDS = 'au-tsi';

	// Organisation

	public const _ASEAN = 'asean';            // Association of Southeast Asian Nations
	public const _ASSOCIATION_OF_SOUTHEAST_ASIAN_NATIONS = 'asean';
	public const _CEFTA = 'cefta';            // Central European Free Trade Agreement
	public const _CENTRAL_EUROPEAN_FREE_TRADE_AGREEMENT = 'cefta';
	public const _EAC = 'eac';                // East African Community
	public const _EAST_AFRICAN_COMMUNITY = 'eac';
	public const _EU = 'eu';                  // Europe
	public const _EUROPE = 'eu';
	public const _ARAB = 'arab';              // League of Arab States
	public const _LEAGUE_OF_ARAB_STATES = 'arab';
	public const _TURKIC = 'turkic';          // Organisation of Turkic States
	public const _ORGANISATION_OF_TURKIC_STATES = 'turkic';
	public const _PC = 'pc';                  // Pacific Community
	public const _PACIFIC_COMMUNITY = 'pc';
	public const _UN = 'un';                  // United Nations
	public const _UNITED_NATIONS = 'un';

	// Advocacy

	public const _BISEXUAL = 'bisexual';      // Bisexual Pride
	public const _BISEXUAL_PRIDE = 'bisexual';
	public const _GAYMALE = 'gaymale';        // Gay Male Pride
	public const _GAY_MALE_PRIDE = 'gaymale';
	public const _INTERSEX = 'intersex';      // Intersex Pride
	public const _INTERSEX_PRIDE = 'intersex';
	public const _PRIDE = 'pride';            // LGB Pride
	public const _LGB_PRIDE = 'pride';
	public const _LESBIAN = 'lesbian';        // Lesbian Pride
	public const _LESBIAN_PRIDE = 'lesbian';
	public const _NONBINARY = 'nonbinary';    // Nonbinary Pride
	public const _NONBINARY_PRIDE = 'nonbinary';
	public const _PANSEXUAL = 'pansexual';    // Pansexuality Pride
	public const _PANSEXUALITY_PRIDE = 'pansexual';
	public const _TRANS = 'trans';            // Transgender Pride
	public const _TRANSGENDER_PRIDE = 'trans';

	// Historic

	public const _AU_EU = 'au-eu';            // Eureka Flag
	public const _EUREKA_FLAG = 'au-eu';
	public const _UA_18B = 'ua-18b';          // Zhytomyr Oblast (2002-2003)
	public const _ZHYTOMYR_OBLAST_2002_2003 = 'ua-18b';
}
