<?php
/**
 * P2FlagConstants.php
 *
 * @author Pedro Plowman
 * @copyright Copyright &copy; Pedro Plowman, 2025
 * @link https://github.com/p2made
 * @license MIT
 */

/**
 * @class \p2m\components\P2FlagConstants
 * @package p2made/yii2-p2y2-things
 */

namespace p2m\components;

class P2FlagConstants
{
	const FLAG_ICON   = 'fi';  // Flag Icon
	const FLAG_BUTTON = 'fib'; // Flag Button
	const SQUARE_FLAG = 'fis'; // Flag Icon Square

	/**
	 * flags name
	 */

	// organisation

	const _ASEAN = 'asean'; // Association of Southeast Asian Nations
	const _ASSOCIATION_OF_SOUTHEAST_ASIAN_NATIONS = 'asean';
	const  = 'asean';
	const _CEFTA = 'cefta'; // Central European Free Trade Agreement
	const _CENTRAL_EUROPEAN_FREE_TRADE_AGREEMENT = 'cefta';
	const  = 'cefta';
	const _EAC = 'eac'; // East African Community
	const _EAST_AFRICAN_COMMUNITY = 'eac';
	const  = 'eac';
	const _EU = 'eu'; // European Union
	const _EUROPE = 'eu';
	const  = 'eu';
	const _ARAB = 'arab'; // League of Arab States
	const _LEAGUE_OF_ARAB_STATES = 'arab';
	const  = 'arab';
	const _TURKIC = 'turkic'; // Organisation of Turkic States
	const _ORGANISATION_OF_TURKIC_STATES = 'turkic';
	const  = 'turkic';
	const _PC = 'pc'; // Pacific Community
	const _PACIFIC_COMMUNITY = 'pc';
	const  = 'pc';
	const _UN = 'un'; // United Nations
	const _UNITED_NATIONS = 'un';
	const  = 'un';

	// other

	const _PRIDE = 'pride'; // LGB Pride
	const _LGB_PRIDE = 'pride';
	const  = 'pride';
	const _TRANS = 'trans'; // Trans Pride
	const _TRANS_PRIDE = 'trans';
	const  = 'trans';

	// Africa

	const _DZ = 'dz'; // Algeria
	const _ALGERIA = 'dz';
	const  = 'dz';
	const _AO = 'ao'; // Angola
	const _ANGOLA = 'ao';
	const  = 'ao';
	const _SH_AC = 'sh-ac'; // Ascension Island
	const _ASCENSION_ISLAND = 'sh-ac';
	const  = 'sh-ac';
	const _BJ = 'bj'; // Benin
	const _BENIN = 'bj';
	const  = 'bj';
	const _BW = 'bw'; // Botswana
	const _BOTSWANA = 'bw';
	const  = 'bw';
	const _BF = 'bf'; // Burkina Faso
	const _BURKINA_FASO = 'bf';
	const  = 'bf';
	const _BI = 'bi'; // Burundi
	const _BURUNDI = 'bi';
	const  = 'bi';
	const _CV = 'cv'; // Cabo Verde
	const _CABO_VERDE = 'cv';
	const  = 'cv';
	const _CM = 'cm'; // Cameroon
	const _CAMEROON = 'cm';
	const  = 'cm';
	const _CF = 'cf'; // Central African Republic
	const _CENTRAL_AFRICAN_REPUBLIC = 'cf';
	const  = 'cf';
	const _TD = 'td'; // Chad
	const _CHAD = 'td';
	const  = 'td';
	const _KM = 'km'; // Comoros
	const _COMOROS = 'km';
	const  = 'km';
	const _CI = 'ci'; // Côte d'Ivoire
	const _COTE_DIVOIRE = 'ci';
	const  = 'ci';
	const _CD = 'cd'; // Democratic Republic of the Congo
	const _DEMOCRATIC_REPUBLIC_OF_THE_CONGO = 'cd';
	const  = 'cd';
	const _DJ = 'dj'; // Djibouti
	const _DJIBOUTI = 'dj';
	const  = 'dj';
	const _EG = 'eg'; // Egypt
	const _EGYPT = 'eg';
	const  = 'eg';
	const _GQ = 'gq'; // Equatorial Guinea
	const _EQUATORIAL_GUINEA = 'gq';
	const  = 'gq';
	const _ER = 'er'; // Eritrea
	const _ERITREA = 'er';
	const  = 'er';
	const _SZ = 'sz'; // Eswatini
	const _ESWATINI = 'sz';
	const  = 'sz';
	const _ET = 'et'; // Ethiopia
	const _ETHIOPIA = 'et';
	const  = 'et';
	const _TF = 'tf'; // French Southern Territories
	const _FRENCH_SOUTHERN_TERRITORIES = 'tf';
	const  = 'tf';
	const _GA = 'ga'; // Gabon
	const _GABON = 'ga';
	const  = 'ga';
	const _GM = 'gm'; // Gambia
	const _GAMBIA = 'gm';
	const  = 'gm';
	const _GH = 'gh'; // Ghana
	const _GHANA = 'gh';
	const  = 'gh';
	const _GN = 'gn'; // Guinea
	const _GUINEA = 'gn';
	const  = 'gn';
	const _GW = 'gw'; // Guinea-Bissau
	const _GUINEA_BISSAU = 'gw';
	const  = 'gw';
	const _KE = 'ke'; // Kenya
	const _KENYA = 'ke';
	const  = 'ke';
	const _LS = 'ls'; // Lesotho
	const _LESOTHO = 'ls';
	const  = 'ls';
	const _LR = 'lr'; // Liberia
	const _LIBERIA = 'lr';
	const  = 'lr';
	const _LY = 'ly'; // Libya
	const _LIBYA = 'ly';
	const  = 'ly';
	const _MG = 'mg'; // Madagascar
	const _MADAGASCAR = 'mg';
	const  = 'mg';
	const _MW = 'mw'; // Malawi
	const _MALAWI = 'mw';
	const  = 'mw';
	const _ML = 'ml'; // Mali
	const _MALI = 'ml';
	const  = 'ml';
	const _MR = 'mr'; // Mauritania
	const _MAURITANIA = 'mr';
	const  = 'mr';
	const _MU = 'mu'; // Mauritius
	const _MAURITIUS = 'mu';
	const  = 'mu';
	const _YT = 'yt'; // Mayotte
	const _MAYOTTE = 'yt';
	const  = 'yt';
	const _MA = 'ma'; // Morocco
	const _MOROCCO = 'ma';
	const  = 'ma';
	const _MZ = 'mz'; // Mozambique
	const _MOZAMBIQUE = 'mz';
	const  = 'mz';
	const _NA = 'na'; // Namibia
	const _NAMIBIA = 'na';
	const  = 'na';
	const _NE = 'ne'; // Niger
	const _NIGER = 'ne';
	const  = 'ne';
	const _NG = 'ng'; // Nigeria
	const _NIGERIA = 'ng';
	const  = 'ng';
	const _CG = 'cg'; // Republic of the Congo
	const _REPUBLIC_OF_THE_CONGO = 'cg';
	const  = 'cg';
	const _RE = 're'; // Réunion
	const _REUNION = 're';
	const  = 're';
	const _RW = 'rw'; // Rwanda
	const _RWANDA = 'rw';
	const  = 'rw';
	const _SH_HL = 'sh-hl'; // Saint Helena
	const _SAINT_HELENA = 'sh-hl';
	const  = 'sh-hl';
	const _SH = 'sh'; // Saint Helena, Ascension & Tristan da Cunha
	const _SAINT_HELENA_ASCENSION_TRISTAN_DA_CUNHA = 'sh';
	const  = 'sh';
	const _ST = 'st'; // Sao Tome & Principe
	const _SAO_TOME_PRINCIPE = 'st';
	const  = 'st';
	const _SN = 'sn'; // Senegal
	const _SENEGAL = 'sn';
	const  = 'sn';
	const _SC = 'sc'; // Seychelles
	const _SEYCHELLES = 'sc';
	const  = 'sc';
	const _SL = 'sl'; // Sierra Leone
	const _SIERRA_LEONE = 'sl';
	const  = 'sl';
	const _SO = 'so'; // Somalia
	const _SOMALIA = 'so';
	const  = 'so';
	const _ZA = 'za'; // South Africa
	const _SOUTH_AFRICA = 'za';
	const  = 'za';
	const _SS = 'ss'; // South Sudan
	const _SOUTH_SUDAN = 'ss';
	const  = 'ss';
	const _SD = 'sd'; // Sudan
	const _SUDAN = 'sd';
	const  = 'sd';
	const _TZ = 'tz'; // Tanzania
	const _TANZANIA = 'tz';
	const  = 'tz';
	const _TG = 'tg'; // Togo
	const _TOGO = 'tg';
	const  = 'tg';
	const _SH_TA = 'sh-ta'; // Tristan da Cunha
	const _TRISTAN_DA_CUNHA = 'sh-ta';
	const  = 'sh-ta';
	const _TN = 'tn'; // Tunisia
	const _TUNISIA = 'tn';
	const  = 'tn';
	const _UG = 'ug'; // Uganda
	const _UGANDA = 'ug';
	const  = 'ug';
	const _EH = 'eh'; // Western Sahara
	const _WESTERN_SAHARA = 'eh';
	const  = 'eh';
	const _ZM = 'zm'; // Zambia
	const _ZAMBIA = 'zm';
	const  = 'zm';
	const _ZW = 'zw'; // Zimbabwe
	const _ZIMBABWE = 'zw';
	const  = 'zw';

	// America, North

	const _AI = 'ai'; // Anguilla
	const _ANGUILLA = 'ai';
	const  = 'ai';
	const _AG = 'ag'; // Antigua & Barbuda
	const _ANTIGUA_BARBUDA = 'ag';
	const  = 'ag';
	const _BS = 'bs'; // Bahamas
	const _BAHAMAS = 'bs';
	const  = 'bs';
	const _BB = 'bb'; // Barbados
	const _BARBADOS = 'bb';
	const  = 'bb';
	const _BZ = 'bz'; // Belize
	const _BELIZE = 'bz';
	const  = 'bz';
	const _BM = 'bm'; // Bermuda
	const _BERMUDA = 'bm';
	const  = 'bm';
	const _CA = 'ca'; // Canada
	const _CANADA = 'ca';
	const  = 'ca';
	const _KY = 'ky'; // Cayman Islands
	const _CAYMAN_ISLANDS = 'ky';
	const  = 'ky';
	const _CR = 'cr'; // Costa Rica
	const _COSTA_RICA = 'cr';
	const  = 'cr';
	const _CU = 'cu'; // Cuba
	const _CUBA = 'cu';
	const  = 'cu';
	const _DM = 'dm'; // Dominica
	const _DOMINICA = 'dm';
	const  = 'dm';
	const _DO = 'do'; // Dominican Republic
	const _DOMINICAN_REPUBLIC = 'do';
	const  = 'do';
	const _SV = 'sv'; // El Salvador
	const _EL_SALVADOR = 'sv';
	const  = 'sv';
	const _GL = 'gl'; // Greenland
	const _GREENLAND = 'gl';
	const  = 'gl';
	const _GD = 'gd'; // Grenada
	const _GRENADA = 'gd';
	const  = 'gd';
	const _GP = 'gp'; // Guadeloupe
	const _GUADELOUPE = 'gp';
	const  = 'gp';
	const _GT = 'gt'; // Guatemala
	const _GUATEMALA = 'gt';
	const  = 'gt';
	const _HT = 'ht'; // Haiti
	const _HAITI = 'ht';
	const  = 'ht';
	const _HN = 'hn'; // Honduras
	const _HONDURAS = 'hn';
	const  = 'hn';
	const _JM = 'jm'; // Jamaica
	const _JAMAICA = 'jm';
	const  = 'jm';
	const _MQ = 'mq'; // Martinique
	const _MARTINIQUE = 'mq';
	const  = 'mq';
	const _MX = 'mx'; // Mexico
	const _MEXICO = 'mx';
	const  = 'mx';
	const _MS = 'ms'; // Montserrat
	const _MONTSERRAT = 'ms';
	const  = 'ms';
	const _NI = 'ni'; // Nicaragua
	const _NICARAGUA = 'ni';
	const  = 'ni';
	const _PA = 'pa'; // Panama
	const _PANAMA = 'pa';
	const  = 'pa';
	const _PR = 'pr'; // Puerto Rico
	const _PUERTO_RICO = 'pr';
	const  = 'pr';
	const _BL = 'bl'; // Saint Barthélemy
	const _SAINT_BARTHELEMY = 'bl';
	const  = 'bl';
	const _KN = 'kn'; // Saint Kitts & Nevis
	const _SAINT_KITTS_NEVIS = 'kn';
	const  = 'kn';
	const _LC = 'lc'; // Saint Lucia
	const _SAINT_LUCIA = 'lc';
	const  = 'lc';
	const _MF = 'mf'; // Saint Martin
	const _SAINT_MARTIN = 'mf';
	const  = 'mf';
	const _PM = 'pm'; // Saint Pierre & Miquelon
	const _SAINT_PIERRE_MIQUELON = 'pm';
	const  = 'pm';
	const _VC = 'vc'; // Saint Vincent & the Grenadines
	const _SAINT_VINCENT_THE_GRENADINES = 'vc';
	const  = 'vc';
	const _SX = 'sx'; // Sint Maarten
	const _SINT_MAARTEN = 'sx';
	const  = 'sx';
	const _TC = 'tc'; // Turks & Caicos Islands
	const _TURKS_CAICOS_ISLANDS = 'tc';
	const  = 'tc';
	const _UM = 'um'; // United States Minor Outlying Islands
	const _UNITED_STATES_MINOR_OUTLYING_ISLANDS = 'um';
	const  = 'um';
	const _US = 'us'; // United States of America
	const _UNITED_STATES_OF_AMERICA = 'us';
	const  = 'us';
	const _VG = 'vg'; // Virgin Islands (British)
	const _VIRGIN_ISLANDS_BRITISH = 'vg';
	const  = 'vg';
	const _VI = 'vi'; // Virgin Islands (US)
	const _VIRGIN_ISLANDS_US = 'vi';
	const  = 'vi';

	// America, South

	const _AR = 'ar'; // Argentina
	const _ARGENTINA = 'ar';
	const  = 'ar';
	const _AW = 'aw'; // Aruba
	const _ARUBA = 'aw';
	const  = 'aw';
	const _BO = 'bo'; // Bolivia
	const _BOLIVIA = 'bo';
	const  = 'bo';
	const _BQ = 'bq'; // Bonaire, Sint Eustatius & Saba
	const _BONAIRE_SINT_EUSTATIUS_SABA = 'bq';
	const  = 'bq';
	const _BR = 'br'; // Brazil
	const _BRAZIL = 'br';
	const  = 'br';
	const _CL = 'cl'; // Chile
	const _CHILE = 'cl';
	const  = 'cl';
	const _CO = 'co'; // Colombia
	const _COLOMBIA = 'co';
	const  = 'co';
	const _CW = 'cw'; // Curaçao
	const _CURACAO = 'cw';
	const  = 'cw';
	const _EC = 'ec'; // Ecuador
	const _ECUADOR = 'ec';
	const  = 'ec';
	const _FK = 'fk'; // Falkland Islands
	const _FALKLAND_ISLANDS = 'fk';
	const  = 'fk';
	const _GF = 'gf'; // French Guiana
	const _FRENCH_GUIANA = 'gf';
	const  = 'gf';
	const _GY = 'gy'; // Guyana
	const _GUYANA = 'gy';
	const  = 'gy';
	const _PY = 'py'; // Paraguay
	const _PARAGUAY = 'py';
	const  = 'py';
	const _PE = 'pe'; // Peru
	const _PERU = 'pe';
	const  = 'pe';
	const _SR = 'sr'; // Suriname
	const _SURINAME = 'sr';
	const  = 'sr';
	const _TT = 'tt'; // Trinidad & Tobago
	const _TRINIDAD_TOBAGO = 'tt';
	const  = 'tt';
	const _UY = 'uy'; // Uruguay
	const _URUGUAY = 'uy';
	const  = 'uy';
	const _VE = 've'; // Venezuela
	const _VENEZUELA = 've';
	const  = 've';

	// Antarctica

	const _AQ = 'aq'; // Antarctica
	const _ANTARCTICA = 'aq';
	const  = 'aq';
	const _BV = 'bv'; // Bouvet Island
	const _BOUVET_ISLAND = 'bv';
	const  = 'bv';
	const _HM = 'hm'; // Heard Island & McDonald Islands
	const _HEARD_ISLAND_MCDONALD_ISLANDS = 'hm';
	const  = 'hm';
	const _GS = 'gs'; // South Georgia & the South Sandwich Islands
	const _SOUTH_GEORGIA_THE_SOUTH_SANDWICH_ISLANDS = 'gs';
	const  = 'gs';

	// Asia

	const _AF = 'af'; // Afghanistan
	const _AFGHANISTAN = 'af';
	const  = 'af';
	const _AM = 'am'; // Armenia
	const _ARMENIA = 'am';
	const  = 'am';
	const _AZ = 'az'; // Azerbaijan
	const _AZERBAIJAN = 'az';
	const  = 'az';
	const _BH = 'bh'; // Bahrain
	const _BAHRAIN = 'bh';
	const  = 'bh';
	const _BALK = 'balk'; // Balkars
	const _BALKARS = 'balk';
	const  = 'balk';
	const _BD = 'bd'; // Bangladesh
	const _BANGLADESH = 'bd';
	const  = 'bd';
	const _BT = 'bt'; // Bhutan
	const _BHUTAN = 'bt';
	const  = 'bt';
	const _IO = 'io'; // British Indian Ocean Territory
	const _BRITISH_INDIAN_OCEAN_TERRITORY = 'io';
	const  = 'io';
	const _BN = 'bn'; // Brunei Darussalam
	const _BRUNEI_DARUSSALAM = 'bn';
	const  = 'bn';
	const _RU_BU = 'ru-bu'; // Buryatia
	const _BURYATIA = 'ru-bu';
	const  = 'ru-bu';
	const _KH = 'kh'; // Cambodia
	const _CAMBODIA = 'kh';
	const  = 'kh';
	const _CN = 'cn'; // China
	const _CHINA = 'cn';
	const  = 'cn';
	const _CX = 'cx'; // Christmas Island
	const _CHRISTMAS_ISLAND = 'cx';
	const  = 'cx';
	const _CHLM = 'chlm'; // Chulym
	const _CHULYM = 'chlm';
	const  = 'chlm';
	const _CC = 'cc'; // Cocos (Keeling) Islands
	const _COCOS_ISLANDS = 'cc';
	const _KEELING_ISLANDS = 'cc';
	const _CN_ET = 'cn-et'; // East Turkestan
	const _EAST_TURKESTAN = 'cn-et';
	const  = 'cn-et';
	const _GE = 'ge'; // Georgia
	const _GEORGIA = 'ge';
	const  = 'ge';
	const _HAZST = 'hazst'; // Hazaristan
	const _HAZARISTAN = 'hazst';
	const  = 'hazst';
	const _HAZ = 'haz'; // Hazarra
	const _HAZARRA = 'haz';
	const  = 'haz';
	const _HK = 'hk'; // Hong Kong
	const _HONG_KONG = 'hk';
	const  = 'hk';
	const _IN = 'in'; // India
	const _INDIA = 'in';
	const  = 'in';
	const _ID = 'id'; // Indonesia
	const _INDONESIA = 'id';
	const  = 'id';
	const _IR = 'ir'; // Iran
	const _IRAN = 'ir';
	const  = 'ir';
	const _IQ = 'iq'; // Iraq
	const _IRAQ = 'iq';
	const  = 'iq';
	const _IL = 'il'; // Israel
	const _ISRAEL = 'il';
	const  = 'il';
	const _JP = 'jp'; // Japan
	const _JAPAN = 'jp';
	const  = 'jp';
	const _JO = 'jo'; // Jordan
	const _JORDAN = 'jo';
	const  = 'jo';
	const _RU_KB = 'ru-kb'; // Kabardino-Balkaria
	const _KABARDINO_BALKARIA = 'ru-kb';
	const  = 'ru-kb';
	const _KRCH = 'krch'; // Karachays
	const _KARACHAYS = 'krch';
	const  = 'krch';
	const _KZ = 'kz'; // Kazakhstan
	const _KAZAKHSTAN = 'kz';
	const  = 'kz';
	const _KKA = 'kka'; // Khakas
	const _KHAKAS = 'kka';
	const  = 'kka';
	const _RU_KK = 'ru-kk'; // Khakassia
	const _KHAKASSIA = 'ru-kk';
	const  = 'ru-kk';
	const _RU_KYA = 'ru-kya'; // Krasnoyarsk Krai
	const _KRASNOYARSK_KRAI = 'ru-kya';
	const  = 'ru-kya';
	const _KW = 'kw'; // Kuwait
	const _KUWAIT = 'kw';
	const  = 'kw';
	const _KG = 'kg'; // Kyrgyzstan
	const _KYRGYZSTAN = 'kg';
	const  = 'kg';
	const _LA = 'la'; // Laos
	const _LAOS = 'la';
	const  = 'la';
	const _LB = 'lb'; // Lebanon
	const _LEBANON = 'lb';
	const  = 'lb';
	const _MO = 'mo'; // Macau
	const _MACAU = 'mo';
	const  = 'mo';
	const _MY = 'my'; // Malaysia
	const _MALAYSIA = 'my';
	const  = 'my';
	const _MV = 'mv'; // Maldives
	const _MALDIVES = 'mv';
	const  = 'mv';
	const _MN = 'mn'; // Mongolia
	const _MONGOLIA = 'mn';
	const  = 'mn';
	const _MM = 'mm'; // Myanmar
	const _MYANMAR = 'mm';
	const  = 'mm';
	const _NP = 'np'; // Nepal
	const _NEPAL = 'np';
	const  = 'np';
	const _NOG = 'nog'; // Nogais
	const _NOGAIS = 'nog';
	const  = 'nog';
	const _KP = 'kp'; // North Korea
	const _NORTH_KOREA = 'kp';
	const  = 'kp';
	const _OM = 'om'; // Oman
	const _OMAN = 'om';
	const  = 'om';
	const _PK = 'pk'; // Pakistan
	const _PAKISTAN = 'pk';
	const  = 'pk';
	const _PH = 'ph'; // Philippines
	const _PHILIPPINES = 'ph';
	const  = 'ph';
	const _QA = 'qa'; // Qatar
	const _QATAR = 'qa';
	const  = 'qa';
	const _SA = 'sa'; // Saudi Arabia
	const _SAUDI_ARABIA = 'sa';
	const  = 'sa';
	const _SG = 'sg'; // Singapore
	const _SINGAPORE = 'sg';
	const  = 'sg';
	const _KR = 'kr'; // South Korea
	const _SOUTH_KOREA = 'kr';
	const  = 'kr';
	const _LK = 'lk'; // Sri Lanka
	const _SRI_LANKA = 'lk';
	const  = 'lk';
	const _PS = 'ps'; // State of Palestine
	const _STATE_OF_PALESTINE = 'ps';
	const  = 'ps';
	const _SY = 'sy'; // Syria
	const _SYRIA = 'sy';
	const  = 'sy';
	const _TW = 'tw'; // Taiwan
	const _TAIWAN = 'tw';
	const  = 'tw';
	const _TJ = 'tj'; // Tajikistan
	const _TAJIKISTAN = 'tj';
	const  = 'tj';
	const _RU_TDN = 'ru-tdn'; // Taymyrsky Dolgano-Nenetsky District
	const _TAYMYRSKY_DOLGANO_NENETSKY_DISTRICT = 'ru-tdn';
	const  = 'ru-tdn';
	const _TH = 'th'; // Thailand
	const _THAILAND = 'th';
	const  = 'th';
	const _TL = 'tl'; // Timor-Leste
	const _TIMOR_LESTE = 'tl';
	const  = 'tl';
	const _RU_TOM = 'ru-tom'; // Tomsk Oblast
	const _TOMSK_OBLAST = 'ru-tom';
	const  = 'ru-tom';
	const _TR = 'tr'; // Türkiye
	const _TURKIYE = 'tr';
	const  = 'tr';
	const _TM = 'tm'; // Turkmenistan
	const _TURKMENISTAN = 'tm';
	const  = 'tm';
	const _RU_TY = 'ru-ty'; // Tuva
	const _TUVA = 'ru-ty';
	const  = 'ru-ty';
	const _AE = 'ae'; // United Arab Emirates
	const _UNITED_ARAB_EMIRATES = 'ae';
	const  = 'ae';
	const _UZ = 'uz'; // Uzbekistan
	const _UZBEKISTAN = 'uz';
	const  = 'uz';
	const _VN = 'vn'; // Vietnam
	const _VIETNAM = 'vn';
	const  = 'vn';
	const _YE = 'ye'; // Yemen
	const _YEMEN = 'ye';
	const  = 'ye';

	// Australia

	const _AU_AA = 'au-aa'; // Aboriginal Australians
	const _ABORIGINAL_AUSTRALIANS = 'au-aa';
	const  = 'au-aa';
	const _AU = 'au'; // Australia
	const _AUSTRALIA = 'au';
	const  = 'au';
	const _AU_EU = 'au-eu'; // Eureka Flag
	const _EUREKA_FLAG = 'au-eu';
	const  = 'au-eu';
	const _AU_TSI = 'au-tsi'; // Torres Strait Islands
	const _TORRES_STRAIT_ISLANDS = 'au-tsi';
	const  = 'au-tsi';

	// Europe

	const _AX = 'ax'; // Aland Islands
	const _ALAND_ISLANDS = 'ax';
	const  = 'ax';
	const _AL = 'al'; // Albania
	const _ALBANIA = 'al';
	const  = 'al';
	const _RU_AL = 'ru-al'; // Altai Republic
	const _ALTAI_REPUBLIC = 'ru-al';
	const  = 'ru-al';
	const _AD = 'ad'; // Andorra
	const _ANDORRA = 'ad';
	const  = 'ad';
	const _RU_AST = 'ru-ast'; // Astrakhan Oblast
	const _ASTRAKHAN_OBLAST = 'ru-ast';
	const  = 'ru-ast';
	const _AT = 'at'; // Austria
	const _AUSTRIA = 'at';
	const  = 'at';
	const _PT_20 = 'pt-20'; // Azores
	const _AZORES = 'pt-20';
	const  = 'pt-20';
	const _ES_IB = 'es-ib'; // Balearic Islands
	const _BALEARIC_ISLANDS = 'es-ib';
	const  = 'es-ib';
	const _RU_BA = 'ru-ba'; // Bashkortostan
	const _BASHKORTOSTAN = 'ru-ba';
	const  = 'ru-ba';
	const _ES_PV = 'es-pv'; // Basque Country
	const _BASQUE_COUNTRY = 'es-pv';
	const  = 'es-pv';
	const _BY = 'by'; // Belarus
	const _BELARUS = 'by';
	const  = 'by';
	const _BE = 'be'; // Belgium
	const _BELGIUM = 'be';
	const  = 'be';
	const _BA = 'ba'; // Bosnia & Herzegovina
	const _BOSNIA_HERZEGOVINA = 'ba';
	const  = 'ba';
	const _BG = 'bg'; // Bulgaria
	const _BULGARIA = 'bg';
	const  = 'bg';
	const _ES_CT = 'es-ct'; // Catalonia
	const _CATALONIA = 'es-ct';
	const  = 'es-ct';
	const _RU_CE = 'ru-ce'; // Chechnya
	const _CHECHNYA = 'ru-ce';
	const  = 'ru-ce';
	const _RU_CHE = 'ru-che'; // Chelyabinsk Oblast
	const _CHELYABINSK_OBLAST = 'ru-che';
	const  = 'ru-che';
	const _RU_CU = 'ru-cu'; // Chuvashia
	const _CHUVASHIA = 'ru-cu';
	const  = 'ru-cu';
	const _CCSS = 'ccss'; // Circassians
	const _CIRCASSIANS = 'ccss';
	const  = 'ccss';
	const _UA_43 = 'ua-43'; // Crimea
	const _CRIMEA = 'ua-43';
	const  = 'ua-43';
	const _UA_CT = 'ua-ct'; // Crimean Tatars
	const _CRIMEAN_TATARS = 'ua-ct';
	const  = 'ua-ct';
	const _HR = 'hr'; // Croatia
	const _CROATIA = 'hr';
	const  = 'hr';
	const _CY = 'cy'; // Cyprus
	const _CYPRUS = 'cy';
	const  = 'cy';
	const _CZ = 'cz'; // Czech Republic
	const _CZECH_REPUBLIC = 'cz';
	const  = 'cz';
	const _RU_DA = 'ru-da'; // Dagestan
	const _DAGESTAN = 'ru-da';
	const  = 'ru-da';
	const _DK = 'dk'; // Denmark
	const _DENMARK = 'dk';
	const  = 'dk';
	const _GB_ENG = 'gb-eng'; // England
	const _ENGLAND = 'gb-eng';
	const  = 'gb-eng';
	const _EE = 'ee'; // Estonia
	const _ESTONIA = 'ee';
	const  = 'ee';
	const _FO = 'fo'; // Faroe Islands
	const _FAROE_ISLANDS = 'fo';
	const  = 'fo';
	const _FI = 'fi'; // Finland
	const _FINLAND = 'fi';
	const  = 'fi';
	const _FR = 'fr'; // France
	const _FRANCE = 'fr';
	const  = 'fr';
	const _ES_GA = 'es-ga'; // Galicia
	const _GALICIA = 'es-ga';
	const  = 'es-ga';
	const _DE = 'de'; // Germany
	const _GERMANY = 'de';
	const  = 'de';
	const _GI = 'gi'; // Gibraltar
	const _GIBRALTAR = 'gi';
	const  = 'gi';
	const _GR = 'gr'; // Greece
	const _GREECE = 'gr';
	const  = 'gr';
	const _GG = 'gg'; // Guernsey
	const _GUERNSEY = 'gg';
	const  = 'gg';
	const _VA = 'va'; // Holy See
	const _HOLY_SEE = 'va';
	const  = 'va';
	const _HU = 'hu'; // Hungary
	const _HUNGARY = 'hu';
	const  = 'hu';
	const _IS = 'is'; // Iceland
	const _ICELAND = 'is';
	const  = 'is';
	const _IE = 'ie'; // Ireland
	const _IRELAND = 'ie';
	const  = 'ie';
	const _IM = 'im'; // Isle of Man
	const _ISLE_OF_MAN = 'im';
	const  = 'im';
	const _IT = 'it'; // Italy
	const _ITALY = 'it';
	const  = 'it';
	const _JE = 'je'; // Jersey
	const _JERSEY = 'je';
	const  = 'je';
	const _RU_KL = 'ru-kl'; // Kalmykia
	const _KALMYKIA = 'ru-kl';
	const  = 'ru-kl';
	const _RU_KC = 'ru-kc'; // Karachay-Cherkessia
	const _KARACHAY_CHERKESSIA = 'ru-kc';
	const  = 'ru-kc';
	const _UZ_QR = 'uz-qr'; // Karakalpakstan
	const _KARAKALPAKSTAN = 'uz-qr';
	const  = 'uz-qr';
	const _XK = 'xk'; // Kosovo
	const _KOSOVO = 'xk';
	const  = 'xk';
	const _KPR = 'kpr'; // Kuban People's Republic
	const _KUBAN_PEOPLES_REPUBLIC = 'kpr';
	const  = 'kpr';
	const _RU_KGN = 'ru-kgn'; // Kurgan Oblast
	const _KURGAN_OBLAST = 'ru-kgn';
	const  = 'ru-kgn';
	const _LV = 'lv'; // Latvia
	const _LATVIA = 'lv';
	const  = 'lv';
	const _LI = 'li'; // Liechtenstein
	const _LIECHTENSTEIN = 'li';
	const  = 'li';
	const _LT = 'lt'; // Lithuania
	const _LITHUANIA = 'lt';
	const  = 'lt';
	const _LU = 'lu'; // Luxembourg
	const _LUXEMBOURG = 'lu';
	const  = 'lu';
	const _PT_30 = 'pt-30'; // Madeira
	const _MADEIRA = 'pt-30';
	const  = 'pt-30';
	const _MT = 'mt'; // Malta
	const _MALTA = 'mt';
	const  = 'mt';
	const _MD = 'md'; // Moldova
	const _MOLDOVA = 'md';
	const  = 'md';
	const _MC = 'mc'; // Monaco
	const _MONACO = 'mc';
	const  = 'mc';
	const _ME = 'me'; // Montenegro
	const _MONTENEGRO = 'me';
	const  = 'me';
	const _ES_NA = 'es-na'; // Navarra
	const _NAVARRA = 'es-na';
	const  = 'es-na';
	const _NL = 'nl'; // Netherlands
	const _NETHERLANDS = 'nl';
	const  = 'nl';
	const _MK = 'mk'; // North Macedonia
	const _NORTH_MACEDONIA = 'mk';
	const  = 'mk';
	const _GB_NIR = 'gb-nir'; // Northern Ireland
	const _NORTHERN_IRELAND = 'gb-nir';
	const  = 'gb-nir';
	const _NO = 'no'; // Norway
	const _NORWAY = 'no';
	const  = 'no';
	const _PL = 'pl'; // Poland
	const _POLAND = 'pl';
	const  = 'pl';
	const _PT = 'pt'; // Portugal
	const _PORTUGAL = 'pt';
	const  = 'pt';
	const _RO = 'ro'; // Romania
	const _ROMANIA = 'ro';
	const  = 'ro';
	const _RU = 'ru'; // Russia
	const _RUSSIA = 'ru';
	const  = 'ru';
	const _RU_SA = 'ru-sa'; // Sakha Republic (Yakutia)
	const _SAKHA_REPUBLIC = 'ru-sa';
	const _YAKUTIA = 'ru-sa';
	const _SM = 'sm'; // San Marino
	const _SAN_MARINO = 'sm';
	const  = 'sm';
	const _GB_SCT = 'gb-sct'; // Scotland
	const _SCOTLAND = 'gb-sct';
	const  = 'gb-sct';
	const _RS = 'rs'; // Serbia
	const _SERBIA = 'rs';
	const  = 'rs';
	const _SK = 'sk'; // Slovakia
	const _SLOVAKIA = 'sk';
	const  = 'sk';
	const _SI = 'si'; // Slovenia
	const _SLOVENIA = 'si';
	const  = 'si';
	const _ES = 'es'; // Spain
	const _SPAIN = 'es';
	const  = 'es';
	const _SJ = 'sj'; // Svalbard & Jan Mayen
	const _SVALBARD_JAN_MAYEN = 'sj';
	const  = 'sj';
	const _RU_SVE = 'ru-sve'; // Sverdlovsk Oblast
	const _SVERDLOVSK_OBLAST = 'ru-sve';
	const  = 'ru-sve';
	const _SE = 'se'; // Sweden
	const _SWEDEN = 'se';
	const  = 'se';
	const _CH = 'ch'; // Switzerland
	const _SWITZERLAND = 'ch';
	const  = 'ch';
	const _RU_TA = 'ru-ta'; // Tatarstan
	const _TATARSTAN = 'ru-ta';
	const  = 'ru-ta';
	const _UA = 'ua'; // Ukraine
	const _UKRAINE = 'ua';
	const  = 'ua';
	const _GB = 'gb'; // United Kingdom
	const _UNITED_KINGDOM = 'gb';
	const  = 'gb';
	const _GB_WLS = 'gb-wls'; // Wales
	const _WALES = 'gb-wls';
	const  = 'gb-wls';

	// Oceania

	const _AS = 'as'; // American Samoa
	const _AMERICAN_SAMOA = 'as';
	const  = 'as';
	const _IC = 'ic'; // Canary Islands
	const _CANARY_ISLANDS = 'ic';
	const  = 'ic';
	const _CP = 'cp'; // Clipperton Island
	const _CLIPPERTON_ISLAND = 'cp';
	const  = 'cp';
	const _CK = 'ck'; // Cook Islands
	const _COOK_ISLANDS = 'ck';
	const  = 'ck';
	const _DG = 'dg'; // Diego Garcia
	const _DIEGO_GARCIA = 'dg';
	const  = 'dg';
	const _FM = 'fm'; // Federated States of Micronesia
	const _FEDERATED_STATES_OF_MICRONESIA = 'fm';
	const  = 'fm';
	const _FJ = 'fj'; // Fiji
	const _FIJI = 'fj';
	const  = 'fj';
	const _PF = 'pf'; // French Polynesia
	const _FRENCH_POLYNESIA = 'pf';
	const  = 'pf';
	const _GU = 'gu'; // Guam
	const _GUAM = 'gu';
	const  = 'gu';
	const _KI = 'ki'; // Kiribati
	const _KIRIBATI = 'ki';
	const  = 'ki';
	const _MH = 'mh'; // Marshall Islands
	const _MARSHALL_ISLANDS = 'mh';
	const  = 'mh';
	const _NR = 'nr'; // Nauru
	const _NAURU = 'nr';
	const  = 'nr';
	const _NC = 'nc'; // New Caledonia
	const _NEW_CALEDONIA = 'nc';
	const  = 'nc';
	const _NZ = 'nz'; // New Zealand
	const _NEW_ZEALAND = 'nz';
	const  = 'nz';
	const _NU = 'nu'; // Niue
	const _NIUE = 'nu';
	const  = 'nu';
	const _NF = 'nf'; // Norfolk Island
	const _NORFOLK_ISLAND = 'nf';
	const  = 'nf';
	const _MP = 'mp'; // Northern Mariana Islands
	const _NORTHERN_MARIANA_ISLANDS = 'mp';
	const  = 'mp';
	const _PW = 'pw'; // Palau
	const _PALAU = 'pw';
	const  = 'pw';
	const _PG = 'pg'; // Papua New Guinea
	const _PAPUA_NEW_GUINEA = 'pg';
	const  = 'pg';
	const _PN = 'pn'; // Pitcairn
	const _PITCAIRN = 'pn';
	const  = 'pn';
	const _WS = 'ws'; // Samoa
	const _SAMOA = 'ws';
	const  = 'ws';
	const _SB = 'sb'; // Solomon Islands
	const _SOLOMON_ISLANDS = 'sb';
	const  = 'sb';
	const _TK = 'tk'; // Tokelau
	const _TOKELAU = 'tk';
	const  = 'tk';
	const _TO = 'to'; // Tonga
	const _TONGA = 'to';
	const  = 'to';
	const _TV = 'tv'; // Tuvalu
	const _TUVALU = 'tv';
	const  = 'tv';
	const _VU = 'vu'; // Vanuatu
	const _VANUATU = 'vu';
	const  = 'vu';
	const _WF = 'wf'; // Wallis & Futuna
	const _WALLIS_FUTUNA = 'wf';
	const  = 'wf';

	const _XX = 'xx'; // Unknown
	const _UNKNOWN = 'xx';
}
