<?php
/**
 * P2FlagIcons.php
 *
 * @author Pedro Plowman
 * @copyright Copyright &copy; Pedro Plowman, 2025
 * @link https://github.com/p2made
 * @license MIT
 */

/**
 * @class \p2m\components\P2FlagIcons
 * @package p2made/yii2-p2y2-things
 */

namespace p2m\components;

use p2m\components\P2Icons;

class P2FlagIcons extends P2Icons
{
	const SQUARE_FLAG = 'fis'; // Flag Icon Square

	/**
	 * flags name
	 */

	// Unknown/xx is used as fallback

	const _XX = 'xx';                  // Unknown
	const _UNKNOWN = 'xx';

	// Africa

	const _DZ = 'dz';                  // Algeria
	const _ALGERIA = 'dz';
	const _AO = 'ao';                  // Angola
	const _ANGOLA = 'ao';
	const _SH_AC = 'sh-ac';            // Ascension Island
	const _ASCENSION_ISLAND = 'sh-ac';
	const _BJ = 'bj';                  // Benin
	const _BENIN = 'bj';
	const _BW = 'bw';                  // Botswana
	const _BOTSWANA = 'bw';
	const _BF = 'bf';                  // Burkina Faso
	const _BURKINA_FASO = 'bf';
	const _BI = 'bi';                  // Burundi
	const _BURUNDI = 'bi';
	const _CV = 'cv';                  // Cabo Verde
	const _CABO_VERDE = 'cv';
	const _CM = 'cm';                  // Cameroon
	const _CAMEROON = 'cm';
	const _CF = 'cf';                  // Central African Republic
	const _CENTRAL_AFRICAN_REPUBLIC = 'cf';
	const _TD = 'td';                  // Chad
	const _CHAD = 'td';
	const _KM = 'km';                  // Comoros
	const _COMOROS = 'km';
	const _CI = 'ci';                  // Côte d'Ivoire
	const _COTE_DIVOIRE = 'ci';
	const _CD = 'cd';                  // Democratic Republic of the Congo
	const _DEMOCRATIC_REPUBLIC_OF_THE_CONGO = 'cd';
	const _DJ = 'dj';                  // Djibouti
	const _DJIBOUTI = 'dj';
	const _EG = 'eg';                  // Egypt
	const _EGYPT = 'eg';
	const _GQ = 'gq';                  // Equatorial Guinea
	const _EQUATORIAL_GUINEA = 'gq';
	const _ER = 'er';                  // Eritrea
	const _ERITREA = 'er';
	const _SZ = 'sz';                  // Eswatini
	const _ESWATINI = 'sz';
	const _ET = 'et';                  // Ethiopia
	const _ETHIOPIA = 'et';
	const _TF = 'tf';                  // French Southern Territories
	const _FRENCH_SOUTHERN_TERRITORIES = 'tf';
	const _GA = 'ga';                  // Gabon
	const _GABON = 'ga';
	const _GM = 'gm';                  // Gambia
	const _GAMBIA = 'gm';
	const _GH = 'gh';                  // Ghana
	const _GHANA = 'gh';
	const _GN = 'gn';                  // Guinea
	const _GUINEA = 'gn';
	const _GW = 'gw';                  // Guinea-Bissau
	const _GUINEA_BISSAU = 'gw';
	const _KE = 'ke';                  // Kenya
	const _KENYA = 'ke';
	const _LS = 'ls';                  // Lesotho
	const _LESOTHO = 'ls';
	const _LR = 'lr';                  // Liberia
	const _LIBERIA = 'lr';
	const _LY = 'ly';                  // Libya
	const _LIBYA = 'ly';
	const _MG = 'mg';                  // Madagascar
	const _MADAGASCAR = 'mg';
	const _MW = 'mw';                  // Malawi
	const _MALAWI = 'mw';
	const _ML = 'ml';                  // Mali
	const _MALI = 'ml';
	const _MR = 'mr';                  // Mauritania
	const _MAURITANIA = 'mr';
	const _MU = 'mu';                  // Mauritius
	const _MAURITIUS = 'mu';
	const _YT = 'yt';                  // Mayotte
	const _MAYOTTE = 'yt';
	const _MA = 'ma';                  // Morocco
	const _MOROCCO = 'ma';
	const _MZ = 'mz';                  // Mozambique
	const _MOZAMBIQUE = 'mz';
	const _NA = 'na';                  // Namibia
	const _NAMIBIA = 'na';
	const _NE = 'ne';                  // Niger
	const _NIGER = 'ne';
	const _NG = 'ng';                  // Nigeria
	const _NIGERIA = 'ng';
	const _CG = 'cg';                  // Republic of the Congo
	const _REPUBLIC_OF_THE_CONGO = 'cg';
	const _RW = 'rw';                  // Rwanda
	const _RWANDA = 'rw';
	const _RE = 're';                  // Réunion
	const _REUNION = 're';
	const _SH_HL = 'sh-hl';            // Saint Helena
	const _SAINT_HELENA = 'sh-hl';
	const _SH = 'sh';                  // Saint Helena, Ascension and Tristan da Cunha
	const _SAINT_HELENA_ASCENSION_TRISTAN_DA_CUNHA = 'sh';
	const _ST = 'st';                  // Sao Tome and Principe
	const _SAO_TOME_PRINCIPE = 'st';
	const _SN = 'sn';                  // Senegal
	const _SENEGAL = 'sn';
	const _SC = 'sc';                  // Seychelles
	const _SEYCHELLES = 'sc';
	const _SL = 'sl';                  // Sierra Leone
	const _SIERRA_LEONE = 'sl';
	const _SO = 'so';                  // Somalia
	const _SOMALIA = 'so';
	const _ZA = 'za';                  // South Africa
	const _SOUTH_AFRICA = 'za';
	const _SS = 'ss';                  // South Sudan
	const _SOUTH_SUDAN = 'ss';
	const _SD = 'sd';                  // Sudan
	const _SUDAN = 'sd';
	const _TZ = 'tz';                  // Tanzania
	const _TANZANIA = 'tz';
	const _TG = 'tg';                  // Togo
	const _TOGO = 'tg';
	const _SH_TA = 'sh-ta';            // Tristan da Cunha
	const _TRISTAN_DA_CUNHA = 'sh-ta';
	const _TN = 'tn';                  // Tunisia
	const _TUNISIA = 'tn';
	const _UG = 'ug';                  // Uganda
	const _UGANDA = 'ug';
	const _EH = 'eh';                  // Western Sahara
	const _WESTERN_SAHARA = 'eh';
	const _ZM = 'zm';                  // Zambia
	const _ZAMBIA = 'zm';
	const _ZW = 'zw';                  // Zimbabwe
	const _ZIMBABWE = 'zw';

	// Antarctica

	const _AQ = 'aq';                  // Antarctica
	const _ANTARCTICA = 'aq';
	const _GS = 'gs';                  // South Georgia and the South Sandwich Islands
	const _SOUTH_GEORGIA_THE_SOUTH_SANDWICH_ISLANDS = 'gs';

	// Asia

	const _AF = 'af';                  // Afghanistan
	const _AFGHANISTAN = 'af';
	const _RU_AGB = 'ru-agb';          // Agin-Buryat Okrug
	const _AGIN_BURYAT_OKRUG = 'ru-agb';
	const _RU_AL = 'ru-al';            // Altai Republic
	const _ALTAI_REPUBLIC = 'ru-al';
	const _AM = 'am';                  // Armenia
	const _ARMENIA = 'am';
	const _AZ = 'az';                  // Azerbaijan
	const _AZERBAIJAN = 'az';
	const _BH = 'bh';                  // Bahrain
	const _BAHRAIN = 'bh';
	const _BD = 'bd';                  // Bangladesh
	const _BANGLADESH = 'bd';
	const _BT = 'bt';                  // Bhutan
	const _BHUTAN = 'bt';
	const _IO = 'io';                  // British Indian Ocean Territory
	const _BRITISH_INDIAN_OCEAN_TERRITORY = 'io';
	const _BN = 'bn';                  // Brunei Darussalam
	const _BRUNEI_DARUSSALAM = 'bn';
	const _RU_BU = 'ru-bu';            // Buryatia
	const _BURYATIA = 'ru-bu';
	const _KH = 'kh';                  // Cambodia
	const _CAMBODIA = 'kh';
	const _RU_CHE = 'ru-che';          // Chelyabinsk Oblast
	const _CHELYABINSK_OBLAST = 'ru-che';
	const _CN = 'cn';                  // China
	const _CHINA = 'cn';
	const _CX = 'cx';                  // Christmas Island
	const _CHRISTMAS_ISLAND = 'cx';
	const _RU_CHU = 'ru-chu';          // Chukotka Autonomous Okrug
	const _CHUKOTKA_AUTONOMOUS_OKRUG = 'ru-chu';
	const _CC = 'cc';                  // Cocos (Keeling) Islands
	const _COCOS_KEELING_ISLANDS = 'cc';
	const _CN_ET = 'cn-et';            // East Turkestan
	const _EAST_TURKESTAN = 'cn-et';
	const _GE = 'ge';                  // Georgia
	const _GEORGIA = 'ge';
	const _HAZST = 'hazst';            // Hazaristan
	const _HAZARISTAN = 'hazst';
	const _HK = 'hk';                  // Hong Kong
	const _HONG_KONG = 'hk';
	const _IN = 'in';                  // India
	const _INDIA = 'in';
	const _ID = 'id';                  // Indonesia
	const _INDONESIA = 'id';
	const _IR = 'ir';                  // Iran
	const _IRAN = 'ir';
	const _IQ = 'iq';                  // Iraq
	const _IRAQ = 'iq';
	const _RU_IRK = 'ru-irk';          // Irkutsk Oblast
	const _IRKUTSK_OBLAST = 'ru-irk';
	const _IL = 'il';                  // Israel
	const _ISRAEL = 'il';
	const _JP = 'jp';                  // Japan
	const _JAPAN = 'jp';
	const _RU_YEV = 'ru-yev';          // Jewish Autonomous Oblast
	const _JEWISH_AUTONOMOUS_OBLAST = 'ru-yev';
	const _JO = 'jo';                  // Jordan
	const _JORDAN = 'jo';
	const _KZ = 'kz';                  // Kazakhstan
	const _KAZAKHSTAN = 'kz';
	const _RU_KHA = 'ru-kha';          // Khabarovsk Krai
	const _KHABAROVSK_KRAI = 'ru-kha';
	const _RU_KK = 'ru-kk';            // Khakassia
	const _KHAKASSIA = 'ru-kk';
	const _RU_KYA = 'ru-kya';          // Krasnoyarsk Krai
	const _KRASNOYARSK_KRAI = 'ru-kya';
	const _RU_KGN = 'ru-kgn';          // Kurgan Oblast
	const _KURGAN_OBLAST = 'ru-kgn';
	const _KW = 'kw';                  // Kuwait
	const _KUWAIT = 'kw';
	const _KG = 'kg';                  // Kyrgyzstan
	const _KYRGYZSTAN = 'kg';
	const _LA = 'la';                  // Laos
	const _LAOS = 'la';
	const _LB = 'lb';                  // Lebanon
	const _LEBANON = 'lb';
	const _MO = 'mo';                  // Macau
	const _MACAU = 'mo';
	const _MY = 'my';                  // Malaysia
	const _MALAYSIA = 'my';
	const _MV = 'mv';                  // Maldives
	const _MALDIVES = 'mv';
	const _MN = 'mn';                  // Mongolia
	const _MONGOLIA = 'mn';
	const _MM = 'mm';                  // Myanmar
	const _MYANMAR = 'mm';
	const _NP = 'np';                  // Nepal
	const _NEPAL = 'np';
	const _KP = 'kp';                  // North Korea
	const _NORTH_KOREA = 'kp';
	const _RU_NVS = 'ru-nvs';          // Novosibirsk Oblast
	const _NOVOSIBIRSK_OBLAST = 'ru-nvs';
	const _OM = 'om';                  // Oman
	const _OMAN = 'om';
	const _PK = 'pk';                  // Pakistan
	const _PAKISTAN = 'pk';
	const _PH = 'ph';                  // Philippines
	const _PHILIPPINES = 'ph';
	const _QA = 'qa';                  // Qatar
	const _QATAR = 'qa';
	const _RU_SA = 'ru-sa';            // Sakha Republic (Yakutia)
	const _SAKHA_REPUBLIC_YAKUTIA = 'ru-sa';
	const _RU_SAK = 'ru-sak';          // Sakhalin Oblast
	const _SAKHALIN_OBLAST = 'ru-sak';
	const _SA = 'sa';                  // Saudi Arabia
	const _SAUDI_ARABIA = 'sa';
	const _SG = 'sg';                  // Singapore
	const _SINGAPORE = 'sg';
	const _KR = 'kr';                  // South Korea
	const _SOUTH_KOREA = 'kr';
	const _LK = 'lk';                  // Sri Lanka
	const _SRI_LANKA = 'lk';
	const _PS = 'ps';                  // State of Palestine
	const _STATE_OF_PALESTINE = 'ps';
	const _RU_SVE = 'ru-sve';          // Sverdlovsk Oblast
	const _SVERDLOVSK_OBLAST = 'ru-sve';
	const _SY = 'sy';                  // Syria
	const _SYRIA = 'sy';
	const _TW = 'tw';                  // Taiwan
	const _TAIWAN = 'tw';
	const _TJ = 'tj';                  // Tajikistan
	const _TAJIKISTAN = 'tj';
	const _RU_TDN = 'ru-tdn';          // Taymyrsky Dolgano-Nenetsky District
	const _TAYMYRSKY_DOLGANO_NENETSKY_DISTRICT = 'ru-tdn';
	const _TH = 'th';                  // Thailand
	const _THAILAND = 'th';
	const _TL = 'tl';                  // Timor-Leste
	const _TIMOR_LESTE = 'tl';
	const _RU_TOM = 'ru-tom';          // Tomsk Oblast
	const _TOMSK_OBLAST = 'ru-tom';
	const _TM = 'tm';                  // Turkmenistan
	const _TURKMENISTAN = 'tm';
	const _RU_TY = 'ru-ty';            // Tuva
	const _TUVA = 'ru-ty';
	const _TR = 'tr';                  // Türkiye
	const _TURKIYE = 'tr';
	const _AE = 'ae';                  // United Arab Emirates
	const _UNITED_ARAB_EMIRATES = 'ae';
	const _UZ = 'uz';                  // Uzbekistan
	const _UZBEKISTAN = 'uz';
	const _VN = 'vn';                  // Vietnam
	const _VIETNAM = 'vn';
	const _YE = 'ye';                  // Yemen
	const _YEMEN = 'ye';
	const _RU_ZAB = 'ru-zab';          // Zabaykalsky Krai
	const _ZABAYKALSKY_KRAI = 'ru-zab';

	// Europe

	const _RU_AD = 'ru-ad';            // Adygea
	const _ADYGEA = 'ru-ad';
	const _AX = 'ax';                  // Aland Islands
	const _ALAND_ISLANDS = 'ax';
	const _AL = 'al';                  // Albania
	const _ALBANIA = 'al';
	const _AD = 'ad';                  // Andorra
	const _ANDORRA = 'ad';
	const _RU_ARK = 'ru-ark';          // Arkhangelsk Oblast
	const _ARKHANGELSK_OBLAST = 'ru-ark';
	const _RU_AST = 'ru-ast';          // Astrakhan Oblast
	const _ASTRAKHAN_OBLAST = 'ru-ast';
	const _AT = 'at';                  // Austria
	const _AUSTRIA = 'at';
	const _UA_43 = 'ua-43';            // Autonomous Republic of Crimea
	const _AUTONOMOUS_REPUBLIC_OF_CRIMEA = 'ua-43';
	const _PT_20 = 'pt-20';            // Azores
	const _AZORES = 'pt-20';
	const _ES_IB = 'es-ib';            // Balearic Islands
	const _BALEARIC_ISLANDS = 'es-ib';
	const _RU_BA = 'ru-ba';            // Bashkortostan
	const _BASHKORTOSTAN = 'ru-ba';
	const _ES_PV = 'es-pv';            // Basque Country
	const _BASQUE_COUNTRY = 'es-pv';
	const _BY = 'by';                  // Belarus
	const _BELARUS = 'by';
	const _BE = 'be';                  // Belgium
	const _BELGIUM = 'be';
	const _BA = 'ba';                  // Bosnia and Herzegovina
	const _BOSNIA_HERZEGOVINA = 'ba';
	const _RU_BRY = 'ru-bry';          // Bryansk Oblast
	const _BRYANSK_OBLAST = 'ru-bry';
	const _BG = 'bg';                  // Bulgaria
	const _BULGARIA = 'bg';
	const _IC = 'ic';                  // Canary Islands
	const _CANARY_ISLANDS = 'ic';
	const _ES_CT = 'es-ct';            // Catalonia
	const _CATALONIA = 'es-ct';
	const _RU_CE = 'ru-ce';            // Chechnya
	const _CHECHNYA = 'ru-ce';
	const _RU_CU = 'ru-cu';            // Chuvashia
	const _CHUVASHIA = 'ru-cu';
	const _HR = 'hr';                  // Croatia
	const _CROATIA = 'hr';
	const _CY = 'cy';                  // Cyprus
	const _CYPRUS = 'cy';
	const _CZ = 'cz';                  // Czech Republic
	const _CZECH_REPUBLIC = 'cz';
	const _RU_DA = 'ru-da';            // Dagestan
	const _DAGESTAN = 'ru-da';
	const _DK = 'dk';                  // Denmark
	const _DENMARK = 'dk';
	const _UA_14 = 'ua-14';            // Donetsk Oblast
	const _DONETSK_OBLAST = 'ua-14';
	const _GB_ENG = 'gb-eng';          // England
	const _ENGLAND = 'gb-eng';
	const _EE = 'ee';                  // Estonia
	const _ESTONIA = 'ee';
	const _FO = 'fo';                  // Faroe Islands
	const _FAROE_ISLANDS = 'fo';
	const _FI = 'fi';                  // Finland
	const _FINLAND = 'fi';
	const _FR = 'fr';                  // France
	const _FRANCE = 'fr';
	const _ES_GA = 'es-ga';            // Galicia
	const _GALICIA = 'es-ga';
	const _DE = 'de';                  // Germany
	const _GERMANY = 'de';
	const _GI = 'gi';                  // Gibraltar
	const _GIBRALTAR = 'gi';
	const _GR = 'gr';                  // Greece
	const _GREECE = 'gr';
	const _GG = 'gg';                  // Guernsey
	const _GUERNSEY = 'gg';
	const _VA = 'va';                  // Holy See
	const _HOLY_SEE = 'va';
	const _HU = 'hu';                  // Hungary
	const _HUNGARY = 'hu';
	const _IS = 'is';                  // Iceland
	const _ICELAND = 'is';
	const _RU_IN = 'ru-in';            // Ingushetia
	const _INGUSHETIA = 'ru-in';
	const _IE = 'ie';                  // Ireland
	const _IRELAND = 'ie';
	const _IM = 'im';                  // Isle of Man
	const _ISLE_OF_MAN = 'im';
	const _IT = 'it';                  // Italy
	const _ITALY = 'it';
	const _JE = 'je';                  // Jersey
	const _JERSEY = 'je';
	const _RU_KB = 'ru-kb';            // Kabardino-Balkaria
	const _KABARDINO_BALKARIA = 'ru-kb';
	const _RU_KGD = 'ru-kgd';          // Kaliningrad Oblast
	const _KALININGRAD_OBLAST = 'ru-kgd';
	const _RU_KL = 'ru-kl';            // Kalmykia
	const _KALMYKIA = 'ru-kl';
	const _RU_KLU = 'ru-klu';          // Kaluga Oblast
	const _KALUGA_OBLAST = 'ru-klu';
	const _RU_KC = 'ru-kc';            // Karachay-Cherkessia
	const _KARACHAY_CHERKESSIA = 'ru-kc';
	const _UZ_QR = 'uz-qr';            // Karakalpakstan
	const _KARAKALPAKSTAN = 'uz-qr';
	const _RU_KIR = 'ru-kir';          // Kirov Oblast
	const _KIROV_OBLAST = 'ru-kir';
	const _RU_KO = 'ru-ko';            // Komi Republic
	const _KOMI_REPUBLIC = 'ru-ko';
	const _XK = 'xk';                  // Kosovo
	const _KOSOVO = 'xk';
	const _RU_KOS = 'ru-kos';          // Kostroma Oblast
	const _KOSTROMA_OBLAST = 'ru-kos';
	const _RU_KDA = 'ru-kda';          // Krasnodar Krai
	const _KRASNODAR_KRAI = 'ru-kda';
	const _KPR = 'kpr';                // Kuban People's Republic
	const _KUBAN_PEOPLES_REPUBLIC = 'kpr';
	const _RU_KRS = 'ru-krs';          // Kursk Oblast
	const _KURSK_OBLAST = 'ru-krs';
	const _LV = 'lv';                  // Latvia
	const _LATVIA = 'lv';
	const _LI = 'li';                  // Liechtenstein
	const _LIECHTENSTEIN = 'li';
	const _LT = 'lt';                  // Lithuania
	const _LITHUANIA = 'lt';
	const _UA_09 = 'ua-09';            // Luhansk Oblast
	const _LUHANSK_OBLAST = 'ua-09';
	const _LU = 'lu';                  // Luxembourg
	const _LUXEMBOURG = 'lu';
	const _PT_30 = 'pt-30';            // Madeira
	const _MADEIRA = 'pt-30';
	const _MT = 'mt';                  // Malta
	const _MALTA = 'mt';
	const _MD = 'md';                  // Moldova
	const _MOLDOVA = 'md';
	const _MC = 'mc';                  // Monaco
	const _MONACO = 'mc';
	const _ME = 'me';                  // Montenegro
	const _MONTENEGRO = 'me';
	const _RU_MO = 'ru-mo';            // Mordovia
	const _MORDOVIA = 'ru-mo';
	const _RU_MOW = 'ru-mow';          // Moscow
	const _MOSCOW = 'ru-mow';
	const _RU_MOS = 'ru-mos';          // Moscow Oblast
	const _MOSCOW_OBLAST = 'ru-mos';
	const _RU_MUR = 'ru-mur';          // Murmansk Oblast
	const _MURMANSK_OBLAST = 'ru-mur';
	const _ES_NA = 'es-na';            // Navarra
	const _NAVARRA = 'es-na';
	const _NL = 'nl';                  // Netherlands
	const _NETHERLANDS = 'nl';
	const _RU_NIZ = 'ru-niz';          // Nizhny Novgorod Oblast
	const _NIZHNY_NOVGOROD_OBLAST = 'ru-niz';
	const _MK = 'mk';                  // North Macedonia
	const _NORTH_MACEDONIA = 'mk';
	const _RU_SE = 'ru-se';            // North Ossetia–Alania
	const _NORTH_OSSETIAALANIA = 'ru-se';
	const _GB_NIR = 'gb-nir';          // Northern Ireland
	const _NORTHERN_IRELAND = 'gb-nir';
	const _NO = 'no';                  // Norway
	const _NORWAY = 'no';
	const _RU_NGR = 'ru-ngr';          // Novgorod Oblast
	const _NOVGOROD_OBLAST = 'ru-ngr';
	const _RU_ORE = 'ru-ore';          // Orenburg Oblast
	const _ORENBURG_OBLAST = 'ru-ore';
	const _RU_ORL = 'ru-orl';          // Oryol Oblast
	const _ORYOL_OBLAST = 'ru-orl';
	const _RU_PNZ = 'ru-pnz';          // Penza Oblast
	const _PENZA_OBLAST = 'ru-pnz';
	const _RU_PER = 'ru-per';          // Perm Krai
	const _PERM_KRAI = 'ru-per';
	const _PL = 'pl';                  // Poland
	const _POLAND = 'pl';
	const _PT = 'pt';                  // Portugal
	const _PORTUGAL = 'pt';
	const _RU_KR = 'ru-kr';            // Republic of Karelia
	const _REPUBLIC_OF_KARELIA = 'ru-kr';
	const _RO = 'ro';                  // Romania
	const _ROMANIA = 'ro';
	const _RU_ROS = 'ru-ros';          // Rostov Oblast
	const _ROSTOV_OBLAST = 'ru-ros';
	const _RU = 'ru';                  // Russia
	const _RUSSIA = 'ru';
	const _RU_RYA = 'ru-rya';          // Ryazan Oblast
	const _RYAZAN_OBLAST = 'ru-rya';
	const _RU_SPE = 'ru-spe';          // Saint Petersburg
	const _SAINT_PETERSBURG = 'ru-spe';
	const _RU_SAM = 'ru-sam';          // Samara Oblast
	const _SAMARA_OBLAST = 'ru-sam';
	const _SM = 'sm';                  // San Marino
	const _SAN_MARINO = 'sm';
	const _RU_SAR = 'ru-sar';          // Saratov Oblast
	const _SARATOV_OBLAST = 'ru-sar';
	const _GB_SCT = 'gb-sct';          // Scotland
	const _SCOTLAND = 'gb-sct';
	const _RS = 'rs';                  // Serbia
	const _SERBIA = 'rs';
	const _UA_SV = 'ua-sv';            // Sevastopol
	const _SEVASTOPOL = 'ua-sv';
	const _GB_ZET = 'gb-zet';          // Shetland
	const _SHETLAND = 'gb-zet';
	const _SK = 'sk';                  // Slovakia
	const _SLOVAKIA = 'sk';
	const _SI = 'si';                  // Slovenia
	const _SLOVENIA = 'si';
	const _ES = 'es';                  // Spain
	const _SPAIN = 'es';
	const _RU_STA = 'ru-sta';          // Stavropol Krai
	const _STAVROPOL_KRAI = 'ru-sta';
	const _SJ = 'sj';                  // Svalbard and Jan Mayen
	const _SVALBARD_JAN_MAYEN = 'sj';
	const _SE = 'se';                  // Sweden
	const _SWEDEN = 'se';
	const _CH = 'ch';                  // Switzerland
	const _SWITZERLAND = 'ch';
	const _RU_TAM = 'ru-tam';          // Tambov Oblast
	const _TAMBOV_OBLAST = 'ru-tam';
	const _RU_TA = 'ru-ta';            // Tatarstan
	const _TATARSTAN = 'ru-ta';
	const _RU_TUL = 'ru-tul';          // Tula Oblast
	const _TULA_OBLAST = 'ru-tul';
	const _RU_TVE = 'ru-tve';          // Tver Oblast
	const _TVER_OBLAST = 'ru-tve';
	const _RU_UD = 'ru-ud';            // Udmurtia
	const _UDMURTIA = 'ru-ud';
	const _UA = 'ua';                  // Ukraine
	const _UKRAINE = 'ua';
	const _RU_ULY = 'ru-uly';          // Ulyanovsk Oblast
	const _ULYANOVSK_OBLAST = 'ru-uly';
	const _GB = 'gb';                  // United Kingdom
	const _UNITED_KINGDOM = 'gb';
	const _UA_05 = 'ua-05';            // Vinnytsia Oblast
	const _VINNYTSIA_OBLAST = 'ua-05';
	const _UA_07 = 'ua-07';            // Volyn Oblast
	const _VOLYN_OBLAST = 'ua-07';
	const _GB_WLS = 'gb-wls';          // Wales
	const _WALES = 'gb-wls';
	const _RU_YAR = 'ru-yar';          // Yaroslavl Oblast
	const _YAROSLAVL_OBLAST = 'ru-yar';
	const _UA_21 = 'ua-21';            // Zakarpattia Oblast
	const _ZAKARPATTIA_OBLAST = 'ua-21';
	const _UA_23 = 'ua-23';            // Zaporizhzhia Oblast
	const _ZAPORIZHZHIA_OBLAST = 'ua-23';
	const _UA_18 = 'ua-18';            // Zhytomyr Oblast
	const _ZHYTOMYR_OBLAST = 'ua-18';

	// North America

	const _AI = 'ai';                  // Anguilla
	const _ANGUILLA = 'ai';
	const _AG = 'ag';                  // Antigua and Barbuda
	const _ANTIGUA_BARBUDA = 'ag';
	const _BS = 'bs';                  // Bahamas
	const _BAHAMAS = 'bs';
	const _BB = 'bb';                  // Barbados
	const _BARBADOS = 'bb';
	const _BZ = 'bz';                  // Belize
	const _BELIZE = 'bz';
	const _BM = 'bm';                  // Bermuda
	const _BERMUDA = 'bm';
	const _CA = 'ca';                  // Canada
	const _CANADA = 'ca';
	const _KY = 'ky';                  // Cayman Islands
	const _CAYMAN_ISLANDS = 'ky';
	const _CR = 'cr';                  // Costa Rica
	const _COSTA_RICA = 'cr';
	const _CU = 'cu';                  // Cuba
	const _CUBA = 'cu';
	const _DM = 'dm';                  // Dominica
	const _DOMINICA = 'dm';
	const _DO = 'do';                  // Dominican Republic
	const _DOMINICAN_REPUBLIC = 'do';
	const _SV = 'sv';                  // El Salvador
	const _EL_SALVADOR = 'sv';
	const _GL = 'gl';                  // Greenland
	const _GREENLAND = 'gl';
	const _GD = 'gd';                  // Grenada
	const _GRENADA = 'gd';
	const _GP = 'gp';                  // Guadeloupe
	const _GUADELOUPE = 'gp';
	const _GT = 'gt';                  // Guatemala
	const _GUATEMALA = 'gt';
	const _HT = 'ht';                  // Haiti
	const _HAITI = 'ht';
	const _HN = 'hn';                  // Honduras
	const _HONDURAS = 'hn';
	const _JM = 'jm';                  // Jamaica
	const _JAMAICA = 'jm';
	const _MQ = 'mq';                  // Martinique
	const _MARTINIQUE = 'mq';
	const _MX = 'mx';                  // Mexico
	const _MEXICO = 'mx';
	const _MS = 'ms';                  // Montserrat
	const _MONTSERRAT = 'ms';
	const _NI = 'ni';                  // Nicaragua
	const _NICARAGUA = 'ni';
	const _PA = 'pa';                  // Panama
	const _PANAMA = 'pa';
	const _PR = 'pr';                  // Puerto Rico
	const _PUERTO_RICO = 'pr';
	const _BL = 'bl';                  // Saint Barthélemy
	const _SAINT_BARTHELEMY = 'bl';
	const _KN = 'kn';                  // Saint Kitts and Nevis
	const _SAINT_KITTS_NEVIS = 'kn';
	const _LC = 'lc';                  // Saint Lucia
	const _SAINT_LUCIA = 'lc';
	const _MF = 'mf';                  // Saint Martin
	const _SAINT_MARTIN = 'mf';
	const _PM = 'pm';                  // Saint Pierre and Miquelon
	const _SAINT_PIERRE_MIQUELON = 'pm';
	const _VC = 'vc';                  // Saint Vincent and the Grenadines
	const _SAINT_VINCENT_THE_GRENADINES = 'vc';
	const _SX = 'sx';                  // Sint Maarten
	const _SINT_MAARTEN = 'sx';
	const _TC = 'tc';                  // Turks and Caicos Islands
	const _TURKS_CAICOS_ISLANDS = 'tc';
	const _UM = 'um';                  // United States Minor Outlying Islands
	const _UNITED_STATES_MINOR_OUTLYING_ISLANDS = 'um';
	const _US = 'us';                  // United States of America
	const _UNITED_STATES_OF_AMERICA = 'us';
	const _VG = 'vg';                  // Virgin Islands (British)
	const _VIRGIN_ISLANDS_BRITISH = 'vg';
	const _VI = 'vi';                  // Virgin Islands (U.S.)
	const _VIRGIN_ISLANDS_US = 'vi';

	// Oceania

	const _AS = 'as';                  // American Samoa
	const _AMERICAN_SAMOA = 'as';
	const _AU = 'au';                  // Australia
	const _AUSTRALIA = 'au';
	const _BV = 'bv';                  // Bouvet Island
	const _BOUVET_ISLAND = 'bv';
	const _CP = 'cp';                  // Clipperton Island
	const _CLIPPERTON_ISLAND = 'cp';
	const _CK = 'ck';                  // Cook Islands
	const _COOK_ISLANDS = 'ck';
	const _DG = 'dg';                  // Diego Garcia
	const _DIEGO_GARCIA = 'dg';
	const _FM = 'fm';                  // Federated States of Micronesia
	const _FEDERATED_STATES_OF_MICRONESIA = 'fm';
	const _FJ = 'fj';                  // Fiji
	const _FIJI = 'fj';
	const _PF = 'pf';                  // French Polynesia
	const _FRENCH_POLYNESIA = 'pf';
	const _GU = 'gu';                  // Guam
	const _GUAM = 'gu';
	const _HM = 'hm';                  // Heard Island and McDonald Islands
	const _HEARD_ISLAND_MCDONALD_ISLANDS = 'hm';
	const _KI = 'ki';                  // Kiribati
	const _KIRIBATI = 'ki';
	const _MH = 'mh';                  // Marshall Islands
	const _MARSHALL_ISLANDS = 'mh';
	const _NR = 'nr';                  // Nauru
	const _NAURU = 'nr';
	const _NC = 'nc';                  // New Caledonia
	const _NEW_CALEDONIA = 'nc';
	const _NZ = 'nz';                  // New Zealand
	const _NEW_ZEALAND = 'nz';
	const _NU = 'nu';                  // Niue
	const _NIUE = 'nu';
	const _NF = 'nf';                  // Norfolk Island
	const _NORFOLK_ISLAND = 'nf';
	const _MP = 'mp';                  // Northern Mariana Islands
	const _NORTHERN_MARIANA_ISLANDS = 'mp';
	const _PW = 'pw';                  // Palau
	const _PALAU = 'pw';
	const _PG = 'pg';                  // Papua New Guinea
	const _PAPUA_NEW_GUINEA = 'pg';
	const _PN = 'pn';                  // Pitcairn
	const _PITCAIRN = 'pn';
	const _WS = 'ws';                  // Samoa
	const _SAMOA = 'ws';
	const _SB = 'sb';                  // Solomon Islands
	const _SOLOMON_ISLANDS = 'sb';
	const _TK = 'tk';                  // Tokelau
	const _TOKELAU = 'tk';
	const _TO = 'to';                  // Tonga
	const _TONGA = 'to';
	const _TV = 'tv';                  // Tuvalu
	const _TUVALU = 'tv';
	const _VU = 'vu';                  // Vanuatu
	const _VANUATU = 'vu';
	const _WF = 'wf';                  // Wallis and Futuna
	const _WALLIS_FUTUNA = 'wf';

	// South America

	const _AR = 'ar';                  // Argentina
	const _ARGENTINA = 'ar';
	const _AW = 'aw';                  // Aruba
	const _ARUBA = 'aw';
	const _BO = 'bo';                  // Bolivia
	const _BOLIVIA = 'bo';
	const _BQ = 'bq';                  // Bonaire, Sint Eustatius and Saba
	const _BONAIRE_SINT_EUSTATIUS_SABA = 'bq';
	const _BR = 'br';                  // Brazil
	const _BRAZIL = 'br';
	const _CL = 'cl';                  // Chile
	const _CHILE = 'cl';
	const _CO = 'co';                  // Colombia
	const _COLOMBIA = 'co';
	const _CW = 'cw';                  // Curaçao
	const _CURACAO = 'cw';
	const _EC = 'ec';                  // Ecuador
	const _ECUADOR = 'ec';
	const _FK = 'fk';                  // Falkland Islands
	const _FALKLAND_ISLANDS = 'fk';
	const _GF = 'gf';                  // French Guiana
	const _FRENCH_GUIANA = 'gf';
	const _GY = 'gy';                  // Guyana
	const _GUYANA = 'gy';
	const _PY = 'py';                  // Paraguay
	const _PARAGUAY = 'py';
	const _PE = 'pe';                  // Peru
	const _PERU = 'pe';
	const _SR = 'sr';                  // Suriname
	const _SURINAME = 'sr';
	const _TT = 'tt';                  // Trinidad and Tobago
	const _TRINIDAD_TOBAGO = 'tt';
	const _UY = 'uy';                  // Uruguay
	const _URUGUAY = 'uy';
	const _VE = 've';                  // Venezuela
	const _VENEZUELA = 've';

	// People

	const _ABZ = 'abz';                // Abazins
	const _ABAZINS = 'abz';
	const _AU_AA = 'au-aa';            // Aboriginal Australians
	const _ABORIGINAL_AUSTRALIANS = 'au-aa';
	const _CHLM = 'chlm';              // Chulym
	const _CHULYM = 'chlm';
	const _CCSS = 'ccss';              // Circassians
	const _CIRCASSIANS = 'ccss';
	const _CR_TAT = 'cr-tat';          // Crimean Tatars
	const _CRIMEAN_TATARS = 'cr-tat';
	const _HAZ = 'haz';                // Hazarra
	const _HAZARRA = 'haz';
	const _KRCH = 'krch';              // Karachays
	const _KARACHAYS = 'krch';
	const _KKA = 'kka';                // Khakas
	const _KHAKAS = 'kka';
	const _NOG = 'nog';                // Nogais
	const _NOGAIS = 'nog';
	const _PAM = 'pam';                // Pamiris
	const _PAMIRIS = 'pam';
	const _AU_TSI = 'au-tsi';          // Torres Strait Islands
	const _TORRES_STRAIT_ISLANDS = 'au-tsi';

	// Organisation

	const _ASEAN = 'asean';            // Association of Southeast Asian Nations
	const _ASSOCIATION_OF_SOUTHEAST_ASIAN_NATIONS = 'asean';
	const _CEFTA = 'cefta';            // Central European Free Trade Agreement
	const _CENTRAL_EUROPEAN_FREE_TRADE_AGREEMENT = 'cefta';
	const _EAC = 'eac';                // East African Community
	const _EAST_AFRICAN_COMMUNITY = 'eac';
	const _EU = 'eu';                  // Europe
	const _EUROPE = 'eu';
	const _ARAB = 'arab';              // League of Arab States
	const _LEAGUE_OF_ARAB_STATES = 'arab';
	const _TURKIC = 'turkic';          // Organisation of Turkic States
	const _ORGANISATION_OF_TURKIC_STATES = 'turkic';
	const _PC = 'pc';                  // Pacific Community
	const _PACIFIC_COMMUNITY = 'pc';
	const _UN = 'un';                  // United Nations
	const _UNITED_NATIONS = 'un';

	// Advocacy

	const _BISEXUAL = 'bisexual';      // Bisexual Pride
	const _BISEXUAL_PRIDE = 'bisexual';
	const _GAYMALE = 'gaymale';        // Gay Male Pride
	const _GAY_MALE_PRIDE = 'gaymale';
	const _INTERSEX = 'intersex';      // Intersex Pride
	const _INTERSEX_PRIDE = 'intersex';
	const _PRIDE = 'pride';            // LGB Pride
	const _LGB_PRIDE = 'pride';
	const _LESBIAN = 'lesbian';        // Lesbian Pride
	const _LESBIAN_PRIDE = 'lesbian';
	const _NONBINARY = 'nonbinary';    // Nonbinary Pride
	const _NONBINARY_PRIDE = 'nonbinary';
	const _PANSEXUAL = 'pansexual';    // Pansexuality Pride
	const _PANSEXUALITY_PRIDE = 'pansexual';
	const _TRANS = 'trans';            // Transgender Pride
	const _TRANSGENDER_PRIDE = 'trans';

	// Historic

	const _AU_EU = 'au-eu';            // Eureka Flag
	const _EUREKA_FLAG = 'au-eu';
	const _UA_18B = 'ua-18b';          // Zhytomyr Oblast (2002-2003)
	const _ZHYTOMYR_OBLAST_2002_2003 = 'ua-18b';
}
